import Battle from "@/models/Battle";
import trainers from "@/static/trainers";

const battles: { [versionGroup: string]: { [battleSlug: string]: Battle } } = {
    emerald: {
        may_1_treecko: {
            trainer: trainers.emerald_may,
            team: [
                {
                    slug: "torchic",
                    species: "torchic",
                    level: 5,
                    nature: "Calm",
                    ability: {
                        slug: "blaze",
                        name: "Blaze",
                    },
                    moves: [
                        { slug: "scratch", name: "Scratch" },
                        {
                            slug: "growl",
                            name: "Growl",
                        },
                    ],
                    ivs: {
                        hp: 0,
                        atk: 0,
                        spa: 0,
                        def: 0,
                        spd: 0,
                        spe: 0,
                    },
                    evs: {
                        hp: 0,
                        atk: 0,
                        spa: 0,
                        def: 0,
                        spd: 0,
                        spe: 0,
                    },
                },
            ],
            items: [],
        },
        may_1_torchic: {
            trainer: trainers.emerald_may,
            team: [
                {
                    slug: "mudkip",
                    species: "mudkip",
                    level: 5,
                    nature: "Calm",
                    ability: {
                        slug: "torrent",
                        name: "Torrent",
                    },
                    moves: [
                        {
                            slug: "tackle",
                            name: "Tackle",
                        },
                        {
                            slug: "growl",
                            name: "Growl",
                        },
                    ],
                    ivs: {
                        hp: 0,
                        atk: 0,
                        spa: 0,
                        def: 0,
                        spd: 0,
                        spe: 0,
                    },
                    evs: {
                        hp: 0,
                        atk: 0,
                        spa: 0,
                        def: 0,
                        spd: 0,
                        spe: 0,
                    },
                },
            ],
            items: [],
        },
        may_1_mudkip: {
            trainer: trainers.emerald_may,
            team: [
                {
                    slug: "treecko",
                    species: "treecko",
                    nature: "Calm",
                    level: 5,
                    ability: {
                        slug: "overgrow",
                        name: "Overgrow",
                    },
                    moves: [
                        { slug: "pound", name: "Pound" },
                        { slug: "leer", name: "Leer" },
                    ],
                    ivs: {
                        hp: 0,
                        atk: 0,
                        spa: 0,
                        def: 0,
                        spd: 0,
                        spe: 0,
                    },
                    evs: {
                        hp: 0,
                        atk: 0,
                        spa: 0,
                        def: 0,
                        spd: 0,
                        spe: 0,
                    },
                },
            ],
            items: [],
        },
        may_2_treecko: {
            trainer: trainers.emerald_may,
            team: [
                {
                    slug: "wingull",
                    species: "wingull",
                    level: 18,
                    nature: "Modest",
                    ability: { slug: "keen-eye", name: "Keen Eye" },
                    moves: [
                        {
                            slug: "growl",
                            name: "Growl",
                        },
                        { slug: "water-gun", name: "Water Gun" },
                        { slug: "supersonic", name: "Supersonic" },
                        { slug: "wing-attack", name: "Wing Attack" },
                    ],
                    ivs: {
                        hp: 6,
                        atk: 6,
                        spa: 6,
                        def: 6,
                        spd: 6,
                        spe: 6,
                    },
                    evs: {
                        hp: 0,
                        atk: 0,
                        spa: 0,
                        def: 0,
                        spd: 0,
                        spe: 0,
                    },
                },
                {
                    slug: "lombre",
                    species: "lombre",
                    level: 18,
                    ability: {
                        slug: "swift-swim",
                        name: "Swift Swim",
                    },
                    moves: [
                        { slug: "astonish", name: "Astonish" },
                        {
                            slug: "growl",
                            name: "Growl",
                        },
                        { slug: "absorb", name: "Absorb" },
                        { slug: "nature-power", name: "Nature Power" },
                    ],
                    ivs: {
                        hp: 6,
                        atk: 6,
                        spa: 6,
                        def: 6,
                        spd: 6,
                        spe: 6,
                    },
                    evs: {
                        hp: 0,
                        atk: 0,
                        spa: 0,
                        def: 0,
                        spd: 0,
                        spe: 0,
                    },
                },
                {
                    slug: "combusken",
                    species: "combusken",
                    level: 20,
                    nature: "Hasty",
                    ability: {
                        slug: "blaze",
                        name: "Blaze",
                    },
                    moves: [
                        { slug: "focus-energy", name: "Focus Energy" },
                        { slug: "ember", name: "Ember" },
                        { slug: "double-kick", name: "Double Kick" },
                        { slug: "peck", name: "Peck" },
                    ],
                    ivs: {
                        hp: 12,
                        atk: 12,
                        spa: 12,
                        def: 12,
                        spd: 12,
                        spe: 12,
                    },
                    evs: {
                        hp: 0,
                        atk: 0,
                        spa: 0,
                        def: 0,
                        spd: 0,
                        spe: 0,
                    },
                },
            ],
            items: [],
        },
        may_2_torchic: {
            trainer: trainers.emerald_may,
            team: [
                {
                    slug: "lombre",
                    species: "lombre",
                    level: 18,
                    ability: {
                        slug: "swift-swim",
                        name: "Swift Swim",
                    },
                    moves: [
                        { slug: "astonish", name: "Astonish" },
                        {
                            slug: "growl",
                            name: "Growl",
                        },
                        { slug: "absorb", name: "Absorb" },
                        { slug: "nature-power", name: "Nature Power" },
                    ],
                    ivs: {
                        hp: 6,
                        atk: 6,
                        spa: 6,
                        def: 6,
                        spd: 6,
                        spe: 6,
                    },
                    evs: {
                        hp: 0,
                        atk: 0,
                        spa: 0,
                        def: 0,
                        spd: 0,
                        spe: 0,
                    },
                },
                {
                    slug: "slugma",
                    species: "slugma",
                    level: 18,
                    nature: "Bold",
                    ability: { slug: "flame-body", name: "Flame Body" },
                    moves: [
                        { slug: "yawn", name: "Yawn" },
                        { slug: "smog", name: "Smog" },
                        { slug: "ember", name: "Ember" },
                        { slug: "rock-tomb", name: "Rock Tomb" },
                    ],
                    ivs: {
                        hp: 6,
                        atk: 6,
                        spa: 6,
                        def: 6,
                        spd: 6,
                        spe: 6,
                    },
                    evs: {
                        hp: 0,
                        atk: 0,
                        spa: 0,
                        def: 0,
                        spd: 0,
                        spe: 0,
                    },
                },
                {
                    slug: "marshtomp",
                    species: "marshtomp",
                    level: 20,
                    nature: "Hasty",
                    ability: {
                        slug: "torrent",
                        name: "Torrent",
                    },
                    moves: [
                        { slug: "water-gun", name: "Water Gun" },
                        { slug: "bide", name: "Bide" },
                        { slug: "mud-shot", name: "Mud Shot" },
                        { slug: "foresight", name: "Foresight" },
                    ],
                    ivs: {
                        hp: 12,
                        atk: 12,
                        spa: 12,
                        def: 12,
                        spd: 12,
                        spe: 12,
                    },
                    evs: {
                        hp: 0,
                        atk: 0,
                        spa: 0,
                        def: 0,
                        spd: 0,
                        spe: 0,
                    },
                },
            ],
            items: [],
        },
        may_2_mudkip: {
            trainer: trainers.emerald_may,
            team: [
                {
                    slug: "slugma",
                    species: "slugma",
                    level: 18,
                    nature: "Bold",
                    ability: { slug: "flame-body", name: "Flame Body" },
                    moves: [
                        { slug: "yawn", name: "Yawn" },
                        { slug: "smog", name: "Smog" },
                        { slug: "ember", name: "Ember" },
                        { slug: "rock-tomb", name: "Rock Tomb" },
                    ],
                    ivs: {
                        hp: 6,
                        atk: 6,
                        spa: 6,
                        def: 6,
                        spd: 6,
                        spe: 6,
                    },
                    evs: {
                        hp: 0,
                        atk: 0,
                        spa: 0,
                        def: 0,
                        spd: 0,
                        spe: 0,
                    },
                },
                {
                    slug: "wingull",
                    species: "wingull",
                    level: 18,
                    nature: "Modest",
                    ability: { slug: "keen-eye", name: "Keen Eye" },
                    moves: [
                        {
                            slug: "growl",
                            name: "Growl",
                        },
                        { slug: "water-gun", name: "Water Gun" },
                        { slug: "supersonic", name: "Supersonic" },
                        { slug: "wing-attack", name: "Wing Attack" },
                    ],
                    ivs: {
                        hp: 6,
                        atk: 6,
                        spa: 6,
                        def: 6,
                        spd: 6,
                        spe: 6,
                    },
                    evs: {
                        hp: 0,
                        atk: 0,
                        spa: 0,
                        def: 0,
                        spd: 0,
                        spe: 0,
                    },
                },
                {
                    slug: "grovyle",
                    species: "grovyle",
                    level: 20,
                    nature: "Hasty",
                    ability: {
                        slug: "overgrow",
                        name: "Overgrow",
                    },
                    moves: [
                        { slug: "absorb", name: "Absorb" },
                        { slug: "quick-attack", name: "Quick Attack" },
                        { slug: "fury-cutter", name: "Fury Cutter" },
                        { slug: "pursuit", name: "Pursuit" },
                    ],
                    ivs: {
                        hp: 12,
                        atk: 12,
                        spa: 12,
                        def: 12,
                        spd: 12,
                        spe: 12,
                    },
                    evs: {
                        hp: 0,
                        atk: 0,
                        spa: 0,
                        def: 0,
                        spd: 0,
                        spe: 0,
                    },
                },
            ],
            items: [],
        },
        wally_1: {
            trainer: trainers.rse_wally,
            team: [
                {
                    slug: "ralts",
                    species: "ralts",
                    level: 16,
                    nature: "Naughty",
                    ability: { slug: "synchronize", name: "Synchronize" },
                    moves: [
                        { slug: "growl", name: "Growl" },
                        { slug: "confusion", name: "Confusion" },
                        { slug: "double-team", name: "Double Team" },
                        { slug: "teleport", name: "Teleport" },
                    ],
                    ivs: {
                        hp: 3,
                        atk: 3,
                        spa: 3,
                        def: 3,
                        spd: 3,
                        spe: 3,
                    },
                    evs: {
                        hp: 0,
                        atk: 0,
                        spa: 0,
                        def: 0,
                        spd: 0,
                        spe: 0,
                    },
                },
            ],
            items: [],
        },
        roxanne: {
            trainer: trainers.rse_roxanne,
            team: [
                {
                    slug: "geodude",
                    species: "geodude",
                    level: 12,
                    nature: "Docile",
                    ability: { slug: "rock-head", name: "Rock Head" },
                    moves: [
                        { slug: "tackle", name: "Tackle" },
                        { slug: "defense-curl", name: "Defense Curl" },
                        { slug: "rock-throw", name: "Rock Throw" },
                        { slug: "rock-tomb", name: "Rock Tomb" },
                    ],
                    ivs: {
                        hp: 12,
                        atk: 12,
                        spa: 12,
                        def: 12,
                        spd: 12,
                        spe: 12,
                    },
                    evs: {
                        hp: 0,
                        atk: 0,
                        spa: 0,
                        def: 0,
                        spd: 0,
                        spe: 0,
                    },
                },
                {
                    slug: "geodude",
                    species: "geodude",
                    level: 12,
                    nature: "Quiet",
                    ability: { slug: "rock-head", name: "Rock Head" },
                    moves: [
                        {
                            slug: "tackle",
                            name: "Tackle",
                        },
                        { slug: "defense-curl", name: "Defense Curl" },
                        { slug: "rock-throw", name: "Rock Throw" },
                        { slug: "rock-tomb", name: "Rock Tomb" },
                    ],
                    ivs: {
                        hp: 12,
                        atk: 12,
                        spa: 12,
                        def: 12,
                        spd: 12,
                        spe: 12,
                    },
                    evs: {
                        hp: 0,
                        atk: 0,
                        spa: 0,
                        def: 0,
                        spd: 0,
                        spe: 0,
                    },
                },
                {
                    slug: "nosepass",
                    species: "nosepass",
                    level: 15,
                    nature: "Lonely",
                    ability: { slug: "sturdy", name: "Sturdy" },
                    moves: [
                        { slug: "block", name: "Block" },
                        { slug: "harden", name: "Harden" },
                        {
                            slug: "tackle",
                            name: "Tackle",
                        },
                        { slug: "rock-tomb", name: "Rock Tomb" },
                    ],
                    item: {
                        slug: "oran-berry",
                        name: "Oran Berry",
                    },
                    ivs: {
                        hp: 24,
                        atk: 24,
                        spa: 24,
                        def: 24,
                        spd: 24,
                        spe: 24,
                    },
                    evs: {
                        hp: 0,
                        atk: 0,
                        spa: 0,
                        def: 0,
                        spd: 0,
                        spe: 0,
                    },
                },
            ],
            items: ["potion", "potion"],
        },
        brawly: {
            trainer: trainers.rse_brawly,
            team: [
                {
                    slug: "machop",
                    species: "machop",
                    level: 16,
                    nature: "Hardy",
                    ability: { slug: "guts", name: "Guts" },
                    moves: [
                        { slug: "karate-chop", name: "Karate Chop" },
                        { slug: "low-kick", name: "Low Kick" },
                        { slug: "seismic-toss", name: "Sesimic Toss" },
                        { slug: "bulk-up", name: "Bulk Up" },
                    ],
                    ivs: {
                        hp: 12,
                        atk: 12,
                        spa: 12,
                        def: 12,
                        spd: 12,
                        spe: 12,
                    },
                    evs: {
                        hp: 0,
                        atk: 0,
                        spa: 0,
                        def: 0,
                        spd: 0,
                        spe: 0,
                    },
                },
                {
                    slug: "meditite",
                    species: "meditite",
                    level: 16,
                    nature: "Calm",
                    ability: { slug: "pure-power", name: "Pure Power" },
                    moves: [
                        { slug: "focus-punch", name: "Focus Punch" },
                        { slug: "light-screen", name: "Light Screen" },
                        { slug: "reflect", name: "Reflect" },
                        { slug: "bulk-up", name: "Bulk Up" },
                    ],
                    ivs: {
                        hp: 12,
                        atk: 12,
                        spa: 12,
                        def: 12,
                        spd: 12,
                        spe: 12,
                    },
                    evs: {
                        hp: 0,
                        atk: 0,
                        spa: 0,
                        def: 0,
                        spd: 0,
                        spe: 0,
                    },
                },
                {
                    slug: "makuhita",
                    species: "makuhita",
                    level: 19,
                    nature: "Lax",
                    ability: { slug: "thick-fat", name: "Thick Fat" },
                    moves: [
                        { slug: "arm-thrust", name: "Arm Thrust" },
                        { slug: "vital-throw", name: "Vital Throw" },
                        { slug: "reversal", name: "Reversal" },
                        { slug: "bulk-up", name: "Bulk Up" },
                    ],
                    item: {
                        slug: "sitrus-berry",
                        name: "Sitrus Berry",
                    },
                    ivs: {
                        hp: 24,
                        atk: 24,
                        spa: 24,
                        def: 24,
                        spd: 24,
                        spe: 24,
                    },
                    evs: {
                        hp: 0,
                        atk: 0,
                        spa: 0,
                        def: 0,
                        spd: 0,
                        spe: 0,
                    },
                },
            ],
            items: ["super-potion", "super-potion"],
        },
        wattson: {
            trainer: trainers.rse_wattson,
            team: [
                {
                    slug: "voltorb",
                    species: "voltorb",
                    level: 20,
                    nature: "Docile",
                    ability: { slug: "soundproof", name: "Soundproof" },
                    moves: [
                        { slug: "rollout", name: "Rollout" },
                        { slug: "spark", name: "Spark" },
                        { slug: "self-destruct", name: "Self-Destruct" },
                        { slug: "shock-wave", name: "Shock Wave" },
                    ],
                    ivs: {
                        hp: 24,
                        atk: 24,
                        spa: 24,
                        def: 24,
                        spd: 24,
                        spe: 24,
                    },
                    evs: {
                        hp: 0,
                        atk: 0,
                        spa: 0,
                        def: 0,
                        spd: 0,
                        spe: 0,
                    },
                },
                {
                    slug: "electrike",
                    species: "electrike",
                    level: 20,
                    nature: "Serious",
                    ability: { slug: "static", name: "Static" },
                    moves: [
                        { slug: "shock-wave", name: "Shock Wave" },
                        { slug: "leer", name: "Leer" },
                        { slug: "quick-attack", name: "Quick Attack" },
                        { slug: "howl", name: "Howl" },
                    ],
                    ivs: {
                        hp: 24,
                        atk: 24,
                        spa: 24,
                        def: 24,
                        spd: 24,
                        spe: 24,
                    },
                    evs: {
                        hp: 0,
                        atk: 0,
                        spa: 0,
                        def: 0,
                        spd: 0,
                        spe: 0,
                    },
                },
                {
                    slug: "magneton",
                    species: "magneton",
                    level: 22,
                    nature: "Impish",
                    ability: { slug: "magnet-pull", name: "Magnet Pull" },
                    moves: [
                        { slug: "supersonic", name: "Supersonic" },
                        { slug: "thunder-wave", name: "Thunder Wave" },
                        { slug: "shock-wave", name: "Shock Wave" },
                        { slug: "sonic-boom", name: "Sonic Boom" },
                    ],
                    ivs: {
                        hp: 24,
                        atk: 26,
                        spa: 24,
                        def: 24,
                        spd: 24,
                        spe: 24,
                    },
                    evs: {
                        hp: 0,
                        atk: 0,
                        spa: 0,
                        def: 0,
                        spd: 0,
                        spe: 0,
                    },
                },
                {
                    slug: "manectric",
                    species: "manectric",
                    level: 24,
                    nature: "Brave",
                    ability: { slug: "static", name: "Static" },
                    moves: [
                        { slug: "quick-attack", name: "Quick Attack" },
                        { slug: "shock-wave", name: "Shock Wave" },
                        { slug: "thunder-wave", name: "Thunder Wave" },
                        { slug: "howl", name: "Howl" },
                    ],
                    item: {
                        slug: "sitrus-berry",
                        name: "Sitrus Berry",
                    },
                    ivs: {
                        hp: 30,
                        atk: 30,
                        spa: 30,
                        def: 30,
                        spd: 30,
                        spe: 30,
                    },
                    evs: {
                        hp: 0,
                        atk: 0,
                        spa: 0,
                        def: 0,
                        spd: 0,
                        spe: 0,
                    },
                },
            ],
            items: ["super-potion", "super-potion"],
        },
        flannery: {
            trainer: trainers.rse_flannery,
            team: [
                {
                    slug: "numel",
                    species: "numel",
                    level: 24,
                    nature: "Jolly",
                    ability: { slug: "oblivious", name: "Oblivious" },
                    moves: [
                        { slug: "rollout", name: "Rollout" },
                        { slug: "spark", name: "Spark" },
                        { slug: "self-destruct", name: "Self-Destruct" },
                        { slug: "shock-wave", name: "Shock Wave" },
                    ],
                    ivs: {
                        hp: 24,
                        atk: 24,
                        spa: 24,
                        def: 24,
                        spd: 24,
                        spe: 24,
                    },
                    evs: {
                        hp: 0,
                        atk: 0,
                        spa: 0,
                        def: 0,
                        spd: 0,
                        spe: 0,
                    },
                },
                {
                    slug: "slugma",
                    species: "slugma",
                    level: 24,
                    nature: "Calm",
                    ability: { slug: "magma-armor", name: "Magma Armor" },
                    moves: [
                        { slug: "shock-wave", name: "Shock Wave" },
                        { slug: "leer", name: "Leer" },
                        { slug: "quick-attack", name: "Quick Attack" },
                        { slug: "howl", name: "Howl" },
                    ],
                    ivs: {
                        hp: 24,
                        atk: 24,
                        spa: 24,
                        def: 24,
                        spd: 24,
                        spe: 24,
                    },
                    evs: {
                        hp: 0,
                        atk: 0,
                        spa: 0,
                        def: 0,
                        spd: 0,
                        spe: 0,
                    },
                },
                {
                    slug: "camerupt",
                    species: "camerupt",
                    level: 26,
                    nature: "Adamant",
                    ability: { slug: "magma-armor", name: "Magma Armor" },
                    moves: [
                        { slug: "supersonic", name: "Supersonic" },
                        { slug: "thunder-wave", name: "Thunder Wave" },
                        { slug: "shock-wave", name: "Shock Wave" },
                        { slug: "sonic-boom", name: "Sonic Boom" },
                    ],
                    ivs: {
                        hp: 30,
                        atk: 30,
                        spa: 30,
                        def: 30,
                        spd: 30,
                        spe: 30,
                    },
                    evs: {
                        hp: 0,
                        atk: 0,
                        spa: 0,
                        def: 0,
                        spd: 0,
                        spe: 0,
                    },
                },
                {
                    slug: "torkoal",
                    species: "torkoal",
                    level: 29,
                    nature: "Modest",
                    ability: { slug: "white-smoke", name: "White Smoke" },
                    moves: [
                        { slug: "overheat", name: "Overheat" },
                        { slug: "sunny-day", name: "Sunny Day" },
                        { slug: "body-slam", name: "Body Slam" },
                        { slug: "attract", name: "Attract" },
                    ],
                    item: {
                        slug: "white-herb",
                        name: "White Herb",
                    },
                    ivs: {
                        hp: 30,
                        atk: 30,
                        spa: 30,
                        def: 30,
                        spd: 30,
                        spe: 30,
                    },
                    evs: {
                        hp: 0,
                        atk: 0,
                        spa: 0,
                        def: 0,
                        spd: 0,
                        spe: 0,
                    },
                },
            ],
            items: ["super-potion", "super-potion"],
        },
        norman: {
            trainer: trainers.rse_norman,
            team: [
                {
                    slug: "spinda",
                    species: "spinda",
                    level: 27,
                    nature: "Docile",
                    ability: { slug: "own-tempo", name: "Own Tempo" },
                    moves: [
                        { slug: "facade", name: "Facade" },
                        { slug: "psybeam", name: "Psybeam" },
                        { slug: "teeter-dance", name: "Teeter Dance" },
                        { slug: "encore", name: "Encore" },
                    ],
                    ivs: {
                        hp: 24,
                        atk: 24,
                        spa: 24,
                        def: 24,
                        spd: 24,
                        spe: 24,
                    },
                    evs: {
                        hp: 0,
                        atk: 0,
                        spa: 0,
                        def: 0,
                        spd: 0,
                        spe: 0,
                    },
                },
                {
                    slug: "vigoroth",
                    species: "vigoroth",
                    level: 27,
                    nature: "Naive",
                    ability: { slug: "vital-spirit", name: "Vital Spirit" },
                    moves: [
                        { slug: "slash", name: "Slash" },
                        { slug: "facade", name: "Facade" },
                        { slug: "feint-attack", name: "Feint Attack" },
                        { slug: "encore", name: "Encore" },
                    ],
                    ivs: {
                        hp: 24,
                        atk: 24,
                        spa: 24,
                        def: 24,
                        spd: 24,
                        spe: 24,
                    },
                    evs: {
                        hp: 0,
                        atk: 0,
                        spa: 0,
                        def: 0,
                        spd: 0,
                        spe: 0,
                    },
                },
                {
                    slug: "linoone",
                    species: "linoone",
                    level: 29,
                    nature: "Lonely",
                    ability: { slug: "pickup", name: "Pickup" },
                    moves: [
                        { slug: "slash", name: "Slash" },
                        { slug: "facade", name: "Facade" },
                        { slug: "headbutt", name: "Headbutt" },
                        { slug: "belly-drum", name: "Belly Drum" },
                    ],
                    ivs: {
                        hp: 24,
                        atk: 24,
                        spa: 24,
                        def: 24,
                        spd: 24,
                        spe: 24,
                    },
                    evs: {
                        hp: 0,
                        atk: 0,
                        spa: 0,
                        def: 0,
                        spd: 0,
                        spe: 0,
                    },
                },
                {
                    slug: "slaking",
                    species: "slaking",
                    level: 31,
                    nature: "Sassy",
                    ability: { slug: "truant", name: "Truant" },
                    moves: [
                        { slug: "facade", name: "Facade" },
                        { slug: "feint-attack", name: "Feint Attack" },
                        { slug: "counter", name: "Counter" },
                        { slug: "yawn", name: "Yawn" },
                    ],
                    item: { slug: "sitrus-berry", name: "Sitrus Berry" },
                    ivs: {
                        hp: 30,
                        atk: 30,
                        spa: 30,
                        def: 30,
                        spd: 30,
                        spe: 30,
                    },
                    evs: {
                        hp: 0,
                        atk: 0,
                        spa: 0,
                        def: 0,
                        spd: 0,
                        spe: 0,
                    },
                },
            ],
            items: ["hyper-potion", "hyper-potion"],
        },
        winona: {
            trainer: trainers.rse_winona,
            team: [
                {
                    slug: "swablu",
                    species: "swablu",
                    level: 29,
                    nature: "Hasty",
                    ability: { slug: "natural-cure", name: "Natural Cure" },
                    moves: [
                        { slug: "aerial-ace", name: "Aerial Ace" },
                        { slug: "perish-song", name: "Perish Song" },
                        { slug: "mirror-move", name: "Mirror Move" },
                        { slug: "safeguard", name: "Safeguard" },
                    ],
                    ivs: {
                        hp: 25,
                        atk: 25,
                        spa: 25,
                        def: 25,
                        spd: 25,
                        spe: 25,
                    },
                    evs: {
                        hp: 0,
                        atk: 0,
                        spa: 0,
                        def: 0,
                        spd: 0,
                        spe: 0,
                    },
                },
                {
                    slug: "tropius",
                    species: "tropius",
                    level: 29,
                    nature: "Impish",
                    ability: { slug: "chlorophyll", name: "Chlorophyll" },
                    moves: [
                        { slug: "solar-beam", name: "Solar Beam" },
                        { slug: "aerial-ace", name: "Aerial Ace" },
                        { slug: "sunny-day", name: "Sunny Day" },
                        { slug: "synthesis", name: "Synthesis" },
                    ],
                    ivs: {
                        hp: 25,
                        atk: 25,
                        spa: 25,
                        def: 25,
                        spd: 25,
                        spe: 25,
                    },
                    evs: {
                        hp: 0,
                        atk: 0,
                        spa: 0,
                        def: 0,
                        spd: 0,
                        spe: 0,
                    },
                },
                {
                    slug: "pelipper",
                    species: "pelipper",
                    level: 30,
                    nature: "Calm",
                    ability: { slug: "keen-eye", name: "Keen Eye" },
                    moves: [
                        { slug: "aerial-ace", name: "Aerial Ace" },
                        { slug: "water-gun", name: "Water Gun" },
                        { slug: "supersonic", name: "Supersonic" },
                        { slug: "protect", name: "Protect" },
                    ],
                    ivs: {
                        hp: 25,
                        atk: 25,
                        spa: 25,
                        def: 25,
                        spd: 25,
                        spe: 25,
                    },
                    evs: {
                        hp: 0,
                        atk: 0,
                        spa: 0,
                        def: 0,
                        spd: 0,
                        spe: 0,
                    },
                },
                {
                    slug: "skarmory",
                    species: "skarmory",
                    level: 31,
                    nature: "Calm",
                    ability: { slug: "keen-eye", name: "Keen Eye" },
                    moves: [
                        { slug: "aerial-ace", name: "Aerial Ace" },
                        { slug: "steel-wing", name: "Steel Wing" },
                        { slug: "fury-attack", name: "Fury Attack" },
                        { slug: "sand-attack", name: "Sand Attack" },
                    ],
                    ivs: {
                        hp: 25,
                        atk: 25,
                        spa: 25,
                        def: 25,
                        spd: 25,
                        spe: 25,
                    },
                    evs: {
                        hp: 0,
                        atk: 0,
                        spa: 0,
                        def: 0,
                        spd: 0,
                        spe: 0,
                    },
                },
                {
                    slug: "altaria",
                    species: "altaria",
                    level: 33,
                    nature: "Docile",
                    ability: { slug: "natural-cure", name: "Natural Cure" },
                    moves: [
                        { slug: "earthquake", name: "Earthquake" },
                        { slug: "aerial-ace", name: "Aerial Ace" },
                        { slug: "dragon-breath", name: "Dragon Breath" },
                        { slug: "dragon-dance", name: "Dragon Dance" },
                    ],
                    item: { slug: "oran-berry", name: "Oran Berry" },
                    ivs: {
                        hp: 31,
                        atk: 31,
                        spa: 31,
                        def: 31,
                        spd: 31,
                        spe: 31,
                    },
                    evs: {
                        hp: 0,
                        atk: 0,
                        spa: 0,
                        def: 0,
                        spd: 0,
                        spe: 0,
                    },
                },
            ],
            items: ["hyper-potion", "hyper-potion"],
        },
        "tate-and-liza": {
            trainer: trainers.rse_tate_and_liza,
            team: [
                {
                    slug: "xatu",
                    species: "xatu",
                    level: 41,
                    nature: "Docile",
                    ability: { slug: "synchronize", name: "Synchronize" },
                    moves: [
                        { slug: "psychic", name: "Psychic" },
                        { slug: "calm-mind", name: "Calm Mind" },
                        { slug: "sunny-day", name: "Sunny Day" },
                        { slug: "confuse-ray", name: "Confuse Ray" },
                    ],
                    ivs: {
                        hp: 30,
                        atk: 30,
                        spa: 30,
                        def: 30,
                        spd: 30,
                        spe: 30,
                    },
                    evs: {
                        hp: 0,
                        atk: 0,
                        spa: 0,
                        def: 0,
                        spd: 0,
                        spe: 0,
                    },
                },
                {
                    slug: "claydol",
                    species: "claydol",
                    level: 41,
                    nature: "Lax",
                    ability: { slug: "levitate", name: "Levitate" },
                    moves: [
                        { slug: "earthquake", name: "Earthquake" },
                        { slug: "ancient-power", name: "Ancient Power" },
                        { slug: "psychic", name: "Psychic" },
                        { slug: "light-screen", name: "Light Screen" },
                    ],
                    ivs: {
                        hp: 30,
                        atk: 30,
                        spa: 30,
                        def: 30,
                        spd: 30,
                        spe: 30,
                    },
                    evs: {
                        hp: 0,
                        atk: 0,
                        spa: 0,
                        def: 0,
                        spd: 0,
                        spe: 0,
                    },
                },
                {
                    slug: "lunatone",
                    species: "lunatone",
                    level: 42,
                    nature: "Impish",
                    ability: { slug: "levitate", name: "Levitate" },
                    moves: [
                        { slug: "psychic", name: "Psychic" },
                        { slug: "hypnosis", name: "Hypnosis" },
                        { slug: "calm-mind", name: "Calm Mind" },
                        { slug: "light-screen", name: "Light Screen" },
                    ],
                    item: { slug: "sitrus-berry", name: "Sitrus Berry" },
                    ivs: {
                        hp: 30,
                        atk: 30,
                        spa: 30,
                        def: 30,
                        spd: 30,
                        spe: 30,
                    },
                    evs: {
                        hp: 0,
                        atk: 0,
                        spa: 0,
                        def: 0,
                        spd: 0,
                        spe: 0,
                    },
                },
                {
                    slug: "solrock",
                    species: "solrock",
                    level: 42,
                    nature: "Modest",
                    ability: { slug: "levitate", name: "Levitate" },
                    moves: [
                        { slug: "solar-beam", name: "Solar Beam" },
                        { slug: "psychic", name: "Psychic" },
                        { slug: "flamethrower", name: "Flamethrower" },
                        { slug: "sunny-day", name: "Sunny Day" },
                    ],
                    item: { slug: "sitrus-berry", name: "Sitrus Berry" },
                    ivs: {
                        hp: 30,
                        atk: 30,
                        spa: 30,
                        def: 30,
                        spd: 30,
                        spe: 30,
                    },
                    evs: {
                        hp: 0,
                        atk: 0,
                        spa: 0,
                        def: 0,
                        spd: 0,
                        spe: 0,
                    },
                },
            ],
            items: ["hyper-potion", "hyper-potion", "hyper-potion", "hyper-potion"],
        },
        juan: {
            trainer: trainers.emerald_juan,
            team: [
                {
                    slug: "luvdisc",
                    species: "luvdisc",
                    level: 41,
                    nature: "Adamant",
                    ability: { slug: "swift-swim", name: "Swift Swim" },
                    moves: [
                        { slug: "water-pulse", name: "Water Pulse" },
                        { slug: "flail", name: "Flail" },
                        { slug: "sweet-kiss", name: "Sweet Kiss" },
                        { slug: "attract", name: "Attract" },
                    ],
                    ivs: {
                        hp: 24,
                        atk: 24,
                        spa: 24,
                        def: 24,
                        spd: 24,
                        spe: 24,
                    },
                    evs: {
                        hp: 0,
                        atk: 0,
                        spa: 0,
                        def: 0,
                        spd: 0,
                        spe: 0,
                    },
                },
                {
                    slug: "whiscash",
                    species: "whiscash",
                    level: 41,
                    nature: "Hasty",
                    ability: { slug: "oblivious", name: "Oblivious" },
                    moves: [
                        { slug: "water-pulse", name: "Water Pulse" },
                        { slug: "earthquake", name: "Earthquake" },
                        { slug: "rain-dance", name: "Rain Dance" },
                        { slug: "amnesia", name: "Amnesia" },
                    ],
                    ivs: {
                        hp: 24,
                        atk: 24,
                        spa: 24,
                        def: 24,
                        spd: 24,
                        spe: 24,
                    },
                    evs: {
                        hp: 0,
                        atk: 0,
                        spa: 0,
                        def: 0,
                        spd: 0,
                        spe: 0,
                    },
                },
                {
                    slug: "sealeo",
                    species: "sealeo",
                    level: 43,
                    nature: "Naive",
                    ability: { slug: "thick-fat", name: "Thick Fat" },
                    moves: [
                        { slug: "aurora-beam", name: "Aurora Beam" },
                        { slug: "water-pulse", name: "Water Pulse" },
                        { slug: "body-slam", name: "Body Slam" },
                        { slug: "encore", name: "Encore" },
                    ],
                    ivs: {
                        hp: 24,
                        atk: 24,
                        spa: 24,
                        def: 24,
                        spd: 24,
                        spe: 24,
                    },
                    evs: {
                        hp: 0,
                        atk: 0,
                        spa: 0,
                        def: 0,
                        spd: 0,
                        spe: 0,
                    },
                },
                {
                    slug: "crawdaunt",
                    species: "crawdaunt",
                    level: 43,
                    nature: "Adamant",
                    ability: { slug: "hyper-cutter", name: "Hyper Cutter" },
                    moves: [
                        { slug: "crabhammer", name: "Crabhammer" },
                        { slug: "water-pulse", name: "Water Pulse" },
                        { slug: "taunt", name: "Taunt" },
                        { slug: "leer", name: "Leer" },
                    ],
                    ivs: {
                        hp: 24,
                        atk: 24,
                        spa: 24,
                        def: 24,
                        spd: 24,
                        spe: 24,
                    },
                    evs: {
                        hp: 0,
                        atk: 0,
                        spa: 0,
                        def: 0,
                        spd: 0,
                        spe: 0,
                    },
                },
                {
                    slug: "kingdra",
                    species: "kingdra",
                    level: 46,
                    nature: "Naive",
                    ability: { slug: "swift-swim", name: "Swift Swim" },
                    moves: [
                        { slug: "ice-beam", name: "Ice Beam" },
                        { slug: "water-pulse", name: "Water Pulse" },
                        { slug: "double-team", name: "Double Team" },
                        { slug: "rest", name: "Rest" },
                    ],
                    item: { slug: "chesto-berry", name: "Chesto Berry" },
                    ivs: {
                        hp: 30,
                        atk: 30,
                        spa: 30,
                        def: 30,
                        spd: 30,
                        spe: 30,
                    },
                    evs: {
                        hp: 0,
                        atk: 0,
                        spa: 0,
                        def: 0,
                        spd: 0,
                        spe: 0,
                    },
                },
            ],
            items: ["hyper-potion", "hyper-potion"],
        },
        sidney: {
            trainer: trainers.rse_sidney,
            team: [],
            items: ["full-restore", "full-restore"],
        },
        phoebe: {
            trainer: trainers.rse_phoebe,
            team: [],
            items: ["full-restore", "full-restore"],
        },
        glacia: {
            trainer: trainers.rse_glacia,
            team: [],
            items: ["full-restore", "full-restore"],
        },
        drake: {
            trainer: trainers.rse_drake,
            team: [],
            items: ["full-restore", "full-restore"],
        },
        wallace: {
            trainer: trainers.emerald_wallace,
            team: [],
            items: ["full-restore", "full-restore", "full-restore", "full-restore"],
        },
        tabitha_1: {
            trainer: trainers.rse_tabitha,
            team: [
                {
                    slug: "numel",
                    species: "numel",
                    level: 18,
                    nature: "Lax",
                    ability: { slug: "oblivious", name: "Oblivious" },
                    moves: [
                        {
                            slug: "growl",
                            name: "Growl",
                        },
                        {
                            slug: "tackle",
                            name: "Tackle",
                        },
                        { slug: "ember", name: "Ember" },
                    ],
                    ivs: {
                        hp: 6,
                        atk: 6,
                        spa: 6,
                        def: 6,
                        spd: 6,
                        spe: 6,
                    },
                    evs: {
                        hp: 0,
                        atk: 0,
                        spa: 0,
                        def: 0,
                        spd: 0,
                        spe: 0,
                    },
                },
                {
                    slug: "poochyena",
                    species: "poochyena",
                    level: 20,
                    nature: "Bashful",
                    ability: { slug: "run-away", name: "Run Away" },
                    moves: [
                        { slug: "howl", name: "Howl" },
                        { slug: "sand-attack", name: "Sand Attack" },
                        { slug: "bite", name: "Bite" },
                        { slug: "odor-sleuth", name: "Odor Sleuth" },
                    ],
                    ivs: {
                        hp: 6,
                        atk: 6,
                        spa: 6,
                        def: 6,
                        spd: 6,
                        spe: 6,
                    },
                    evs: {
                        hp: 0,
                        atk: 0,
                        spa: 0,
                        def: 0,
                        spd: 0,
                        spe: 0,
                    },
                },
                {
                    slug: "numel",
                    species: "numel",
                    level: 22,
                    nature: "Mild",
                    ability: { slug: "oblivious", name: "Oblivious" },
                    moves: [
                        {
                            slug: "growl",
                            name: "Growl",
                        },
                        {
                            slug: "tackle",
                            name: "Tackle",
                        },
                        { slug: "ember", name: "Ember" },
                        { slug: "magnitude", name: "Magnitude" },
                    ],
                    ivs: {
                        hp: 6,
                        atk: 6,
                        spa: 6,
                        def: 6,
                        spd: 6,
                        spe: 6,
                    },
                    evs: {
                        hp: 0,
                        atk: 0,
                        spa: 0,
                        def: 0,
                        spd: 0,
                        spe: 0,
                    },
                },
                {
                    slug: "zubat",
                    species: "zubat",
                    level: 22,
                    nature: "Rash",
                    ability: { slug: "inner-focus", name: "Inner Focus" },
                    moves: [
                        { slug: "supersonic", name: "Supersonic" },
                        { slug: "astonish", name: "Astonish" },
                        { slug: "bite", name: "Bite" },
                        { slug: "wing-attack", name: "Wing Attack" },
                    ],
                    ivs: {
                        hp: 6,
                        atk: 6,
                        spa: 6,
                        def: 6,
                        spd: 6,
                        spe: 6,
                    },
                    evs: {
                        hp: 0,
                        atk: 0,
                        spa: 0,
                        def: 0,
                        spd: 0,
                        spe: 0,
                    },
                },
            ],
            items: [],
        },
    },
    "heartgold-soulsilver": {
        silver_1_chikorita: {
            trainer: trainers.hgss_silver,
            team: [
                {
                    slug: "cyndaquil",
                    species: "cyndaquil",
                    level: 5,
                    ability: {
                        slug: "blaze",
                        name: "Blaze",
                    },
                    moves: [
                        {
                            slug: "tackle",
                            name: "Tackle",
                        },
                        { slug: "leer", name: "Leer" },
                    ],
                    ivs: {
                        hp: 0,
                        atk: 0,
                        spa: 0,
                        def: 0,
                        spd: 0,
                        spe: 0,
                    },
                    evs: {
                        hp: 0,
                        atk: 0,
                        spa: 0,
                        def: 0,
                        spd: 0,
                        spe: 0,
                    },
                },
            ],
            items: [],
        },
        silver_1_cyndaquil: {
            trainer: trainers.hgss_silver,
            team: [
                {
                    slug: "totodile",
                    species: "totodile",
                    level: 5,
                    ability: {
                        slug: "torrent",
                        name: "Torrent",
                    },
                    moves: [
                        { slug: "scratch", name: "Scratch" },
                        { slug: "leer", name: "Leer" },
                    ],
                    ivs: {
                        hp: 0,
                        atk: 0,
                        spa: 0,
                        def: 0,
                        spd: 0,
                        spe: 0,
                    },
                    evs: {
                        hp: 0,
                        atk: 0,
                        spa: 0,
                        def: 0,
                        spd: 0,
                        spe: 0,
                    },
                },
            ],
            items: [],
        },
        silver_1_totodile: {
            trainer: trainers.hgss_silver,
            team: [
                {
                    slug: "chikorita",
                    species: "chikorita",
                    level: 5,
                    ability: {
                        slug: "overgrow",
                        name: "Overgrow",
                    },
                    moves: [
                        {
                            slug: "tackle",
                            name: "Tackle",
                        },
                        {
                            slug: "growl",
                            name: "Growl",
                        },
                    ],
                    ivs: {
                        hp: 0,
                        atk: 0,
                        spa: 0,
                        def: 0,
                        spd: 0,
                        spe: 0,
                    },
                    evs: {
                        hp: 0,
                        atk: 0,
                        spa: 0,
                        def: 0,
                        spd: 0,
                        spe: 0,
                    },
                },
            ],
            items: [],
        },
        elder_li: {
            trainer: trainers.hgss_elder_li,
            team: [
                {
                    slug: "bellsprout",
                    species: "bellsprout",
                    level: 7,
                    ability: { slug: "chlorophyll", name: "Chlorophyll" },
                    moves: [
                        { slug: "vine-whip", name: "Vine Whip" },
                        { slug: "growth", name: "Growth" },
                    ],
                    ivs: {
                        hp: 0,
                        atk: 0,
                        spa: 0,
                        def: 0,
                        spd: 0,
                        spe: 0,
                    },
                    evs: {
                        hp: 0,
                        atk: 0,
                        spa: 0,
                        def: 0,
                        spd: 0,
                        spe: 0,
                    },
                },
                {
                    slug: "bellsprout",
                    species: "bellsprout",
                    level: 7,
                    ability: { slug: "chlorophyll", name: "Chlorophyll" },
                    moves: [
                        { slug: "vine-whip", name: "Vine Whip" },
                        { slug: "growth", name: "Growth" },
                    ],
                    ivs: {
                        hp: 0,
                        atk: 0,
                        spa: 0,
                        def: 0,
                        spd: 0,
                        spe: 0,
                    },
                    evs: {
                        hp: 0,
                        atk: 0,
                        spa: 0,
                        def: 0,
                        spd: 0,
                        spe: 0,
                    },
                },
                {
                    slug: "hoothoot",
                    species: "hoothoot",
                    level: 10,
                    ability: { slug: "insomnia", name: "Insomnia" },
                    moves: [
                        {
                            slug: "growl",
                            name: "Growl",
                        },
                        { slug: "hypnosis", name: "Hypnosis" },
                        { slug: "peck", name: "Peck" },
                    ],
                    ivs: {
                        hp: 0,
                        atk: 0,
                        spa: 0,
                        def: 0,
                        spd: 0,
                        spe: 0,
                    },
                    evs: {
                        hp: 0,
                        atk: 0,
                        spa: 0,
                        def: 0,
                        spd: 0,
                        spe: 0,
                    },
                },
            ],
            items: [],
        },
        falkner: {
            trainer: trainers.hgss_falkner,
            team: [
                {
                    slug: "pidgey",
                    species: "pidgey",
                    level: 9,
                    ability: { slug: "keen-eye", name: "Keen Eye" },
                    moves: [
                        {
                            slug: "tackle",
                            name: "Tackle",
                        },
                        { slug: "sand-attack", name: "Sand Attack" },
                    ],
                    ivs: {
                        hp: 0,
                        atk: 0,
                        spa: 0,
                        def: 0,
                        spd: 0,
                        spe: 0,
                    },
                    evs: {
                        hp: 0,
                        atk: 0,
                        spa: 0,
                        def: 0,
                        spd: 0,
                        spe: 0,
                    },
                },
                {
                    slug: "pidgeotto",
                    species: "pidgeotto",
                    level: 13,
                    ability: { slug: "keen-eye", name: "Keen Eye" },
                    moves: [
                        {
                            slug: "tackle",
                            name: "Tackle",
                        },
                        { slug: "roost", name: "Roost" },
                        { slug: "gust", name: "Gust" },
                    ],
                    ivs: {
                        hp: 0,
                        atk: 0,
                        spa: 0,
                        def: 0,
                        spd: 0,
                        spe: 0,
                    },
                    evs: {
                        hp: 0,
                        atk: 0,
                        spa: 0,
                        def: 0,
                        spd: 0,
                        spe: 0,
                    },
                },
            ],
            items: [],
        },
    },
};

export default battles;
