import Battle from "@/models/Battle";
import trainers from "@/static/trainers";

const battles: { [versionGroup: string]: { [battleSlug: string]: Battle } } = {
    emerald: {
        may_1_treecko: {
            trainer: trainers.emerald_may,
            team: [
                {
                    slug: "torchic",
                    species: "torchic",
                    level: 5,
                    ability: { slug: "blaze", name: "Blaze" },
                    moves: [
                        { slug: "scratch", name: "Scratch" },
                        { slug: "growl", name: "Growl" },
                    ],
                    ivs: { hp: 0, atk: 0, spa: 0, def: 0, spd: 0, spe: 0 },
                    evs: { hp: 0, atk: 0, spa: 0, def: 0, spd: 0, spe: 0 },
                },
            ],
            items: [],
        },
        may_1_torchic: {
            trainer: trainers.emerald_may,
            team: [
                {
                    slug: "mudkip",
                    species: "mudkip",
                    level: 5,
                    ability: { slug: "torrent", name: "Torrent" },
                    moves: [
                        { slug: "tackle", name: "Tackle" },
                        { slug: "growl", name: "Growl" },
                    ],
                    ivs: { hp: 0, atk: 0, spa: 0, def: 0, spd: 0, spe: 0 },
                    evs: { hp: 0, atk: 0, spa: 0, def: 0, spd: 0, spe: 0 },
                },
            ],
            items: [],
        },
        may_1_mudkip: {
            trainer: trainers.emerald_may,
            team: [
                {
                    slug: "treecko",
                    species: "treecko",
                    level: 5,
                    ability: { slug: "overgrow", name: "Overgrow" },
                    moves: [
                        { slug: "pound", name: "Pound" },
                        { slug: "leer", name: "Leer" },
                    ],
                    ivs: { hp: 0, atk: 0, spa: 0, def: 0, spd: 0, spe: 0 },
                    evs: { hp: 0, atk: 0, spa: 0, def: 0, spd: 0, spe: 0 },
                },
            ],
            items: [],
        },
        may_2_treecko: {
            trainer: trainers.emerald_may,
            team: [
                {
                    slug: "wingull",
                    species: "wingull",
                    level: 18,
                    ability: { slug: "keen-eye", name: "Keen Eye" },
                    moves: [
                        { slug: "growl", name: "Growl" },
                        { slug: "water-gun", name: "Water Gun" },
                        { slug: "supersonic", name: "Supersonic" },
                        { slug: "wing-attack", name: "Wing Attack" },
                    ],
                    ivs: { hp: 6, atk: 6, spa: 6, def: 6, spd: 6, spe: 6 },
                    evs: { hp: 0, atk: 0, spa: 0, def: 0, spd: 0, spe: 0 },
                },
                {
                    slug: "lombre",
                    species: "lombre",
                    level: 18,
                    ability: { slug: "swift-swim", name: "Swift Swim" },
                    moves: [
                        { slug: "astonish", name: "Astonish" },
                        { slug: "growl", name: "Growl" },
                        { slug: "absorb", name: "Absorb" },
                        { slug: "nature-power", name: "Nature Power" },
                    ],
                    ivs: { hp: 6, atk: 6, spa: 6, def: 6, spd: 6, spe: 6 },
                    evs: { hp: 0, atk: 0, spa: 0, def: 0, spd: 0, spe: 0 },
                },
                {
                    slug: "combusken",
                    species: "combusken",
                    level: 20,
                    ability: { slug: "blaze", name: "Blaze" },
                    moves: [
                        { slug: "focus-energy", name: "Focus Energy" },
                        { slug: "ember", name: "Ember" },
                        { slug: "double-kick", name: "Double Kick" },
                        { slug: "peck", name: "Peck" },
                    ],
                    ivs: { hp: 12, atk: 12, spa: 12, def: 12, spd: 12, spe: 12 },
                    evs: { hp: 0, atk: 0, spa: 0, def: 0, spd: 0, spe: 0 },
                },
            ],
            items: [],
        },
        may_2_torchic: {
            trainer: trainers.emerald_may,
            team: [
                {
                    slug: "lombre",
                    species: "lombre",
                    level: 18,
                    ability: { slug: "swift-swim", name: "Swift Swim" },
                    moves: [
                        { slug: "astonish", name: "Astonish" },
                        { slug: "growl", name: "Growl" },
                        { slug: "absorb", name: "Absorb" },
                        { slug: "nature-power", name: "Nature Power" },
                    ],
                    ivs: { hp: 6, atk: 6, spa: 6, def: 6, spd: 6, spe: 6 },
                    evs: { hp: 0, atk: 0, spa: 0, def: 0, spd: 0, spe: 0 },
                },
                {
                    slug: "slugma",
                    species: "slugma",
                    level: 18,
                    ability: { slug: "flame-body", name: "Flame Body" },
                    moves: [
                        { slug: "yawn", name: "Yawn" },
                        { slug: "smog", name: "Smog" },
                        { slug: "ember", name: "Ember" },
                        { slug: "rock-tomb", name: "Rock Tomb" },
                    ],
                    ivs: { hp: 6, atk: 6, spa: 6, def: 6, spd: 6, spe: 6 },
                    evs: { hp: 0, atk: 0, spa: 0, def: 0, spd: 0, spe: 0 },
                },
                {
                    slug: "marshtomp",
                    species: "marshtomp",
                    level: 20,
                    ability: { slug: "torrent", name: "Torrent" },
                    moves: [
                        { slug: "water-gun", name: "Water Gun" },
                        { slug: "bide", name: "Bide" },
                        { slug: "mud-shot", name: "Mud Shot" },
                        { slug: "foresight", name: "Foresight" },
                    ],
                    ivs: { hp: 12, atk: 12, spa: 12, def: 12, spd: 12, spe: 12 },
                    evs: { hp: 0, atk: 0, spa: 0, def: 0, spd: 0, spe: 0 },
                },
            ],
            items: [],
        },
        may_2_mudkip: {
            trainer: trainers.emerald_may,
            team: [
                {
                    slug: "wingull",
                    species: "wingull",
                    level: 18,
                    ability: { slug: "keen-eye", name: "Keen Eye" },
                    moves: [
                        { slug: "growl", name: "Growl" },
                        { slug: "water-gun", name: "Water Gun" },
                        { slug: "supersonic", name: "Supersonic" },
                        { slug: "wing-attack", name: "Wing Attack" },
                    ],
                    ivs: { hp: 6, atk: 6, spa: 6, def: 6, spd: 6, spe: 6 },
                    evs: { hp: 0, atk: 0, spa: 0, def: 0, spd: 0, spe: 0 },
                },
                {
                    slug: "slugma",
                    species: "slugma",
                    level: 18,
                    ability: { slug: "flame-body", name: "Flame Body" },
                    moves: [
                        { slug: "yawn", name: "Yawn" },
                        { slug: "smog", name: "Smog" },
                        { slug: "ember", name: "Ember" },
                        { slug: "rock-tomb", name: "Rock Tomb" },
                    ],
                    ivs: { hp: 6, atk: 6, spa: 6, def: 6, spd: 6, spe: 6 },
                    evs: { hp: 0, atk: 0, spa: 0, def: 0, spd: 0, spe: 0 },
                },
                {
                    slug: "grovyle",
                    species: "grovyle",
                    level: 20,
                    ability: { slug: "overgrow", name: "Overgrow" },
                    moves: [
                        { slug: "absorb", name: "Absorb" },
                        { slug: "quick-attack", name: "Quick Attack" },
                        { slug: "fury-cutter", name: "Fury Cutter" },
                        { slug: "pursuit", name: "Pursuit" },
                    ],
                    ivs: { hp: 12, atk: 12, spa: 12, def: 12, spd: 12, spe: 12 },
                    evs: { hp: 0, atk: 0, spa: 0, def: 0, spd: 0, spe: 0 },
                },
            ],
            items: [],
        },
        may_3_treecko: {
            trainer: trainers.emerald_may,
            team: [
                {
                    slug: "pelipper",
                    species: "pelipper",
                    level: 29,
                    ability: { slug: "keen-eye", name: "Keen Eye" },
                    moves: [
                        { slug: "wing-attack", name: "Wing Attack" },
                        { slug: "supersonic", name: "Supersonic" },
                        { slug: "mist", name: "Mist" },
                        { slug: "protect", name: "Protect" },
                    ],
                    ivs: { hp: 12, atk: 12, spa: 12, def: 12, spd: 12, spe: 12 },
                    evs: { hp: 0, atk: 0, spa: 0, def: 0, spd: 0, spe: 0 },
                },
                {
                    slug: "lombre",
                    species: "lombre",
                    level: 29,
                    ability: { slug: "swift-swim", name: "Swift Swim" },
                    moves: [
                        { slug: "absorb", name: "Absorb" },
                        { slug: "fake-out", name: "Fake Out" },
                        { slug: "nature-power", name: "Nature Power" },
                        { slug: "fury-swipes", name: "Fury Swipes" },
                    ],
                    ivs: { hp: 12, atk: 12, spa: 12, def: 12, spd: 12, spe: 12 },
                    evs: { hp: 0, atk: 0, spa: 0, def: 0, spd: 0, spe: 0 },
                },
                {
                    slug: "combusken",
                    species: "combusken",
                    level: 31,
                    ability: { slug: "blaze", name: "Blaze" },
                    moves: [
                        { slug: "double-kick", name: "Double Kick" },
                        { slug: "bulk-up", name: "Bulk Up" },
                        { slug: "peck", name: "Peck" },
                        { slug: "sand-attack", name: "Sand Attack" },
                    ],
                    ivs: { hp: 18, atk: 18, spa: 18, def: 18, spd: 18, spe: 18 },
                    evs: { hp: 0, atk: 0, spa: 0, def: 0, spd: 0, spe: 0 },
                },
            ],
            items: [],
        },
        may_3_torchic: {
            trainer: trainers.emerald_may,
            team: [
                {
                    slug: "lombre",
                    species: "lombre",
                    level: 29,
                    ability: { slug: "swift-swim", name: "Swift Swim" },
                    moves: [
                        { slug: "absorb", name: "Absorb" },
                        { slug: "fake-out", name: "Fake Out" },
                        { slug: "nature-power", name: "Nature Power" },
                        { slug: "fury-swipes", name: "Fury Swipes" },
                    ],
                    ivs: { hp: 12, atk: 12, spa: 12, def: 12, spd: 12, spe: 12 },
                    evs: { hp: 0, atk: 0, spa: 0, def: 0, spd: 0, spe: 0 },
                },
                {
                    slug: "slugma",
                    species: "slugma",
                    level: 29,
                    ability: { slug: "flame-body", name: "Flame Body" },
                    moves: [
                        { slug: "harden", name: "Harden" },
                        { slug: "amnesia", name: "Amnesia" },
                        { slug: "ember", name: "Ember" },
                        { slug: "rock-throw", name: "Rock Throw" },
                    ],
                    ivs: { hp: 12, atk: 12, spa: 12, def: 12, spd: 12, spe: 12 },
                    evs: { hp: 0, atk: 0, spa: 0, def: 0, spd: 0, spe: 0 },
                },
                {
                    slug: "marshtomp",
                    species: "marshtomp",
                    level: 31,
                    ability: { slug: "torrent", name: "Torrent" },
                    moves: [
                        { slug: "mud-shot", name: "Mud Shot" },
                        { slug: "mud-sport", name: "Mud Sport" },
                        { slug: "foresight", name: "Foresight" },
                        { slug: "take-down", name: "Take Down" },
                    ],
                    ivs: { hp: 18, atk: 18, spa: 18, def: 18, spd: 18, spe: 18 },
                    evs: { hp: 0, atk: 0, spa: 0, def: 0, spd: 0, spe: 0 },
                },
            ],
            items: [],
        },
        may_3_mudkip: {
            trainer: trainers.emerald_may,
            team: [
                {
                    slug: "pelipper",
                    species: "pelipper",
                    level: 29,
                    ability: { slug: "keen-eye", name: "Keen Eye" },
                    moves: [
                        { slug: "wing-attack", name: "Wing Attack" },
                        { slug: "supersonic", name: "Supersonic" },
                        { slug: "mist", name: "Mist" },
                        { slug: "protect", name: "Protect" },
                    ],
                    ivs: { hp: 12, atk: 12, spa: 12, def: 12, spd: 12, spe: 12 },
                    evs: { hp: 0, atk: 0, spa: 0, def: 0, spd: 0, spe: 0 },
                },
                {
                    slug: "slugma",
                    species: "slugma",
                    level: 29,
                    ability: { slug: "flame-body", name: "Flame Body" },
                    moves: [
                        { slug: "harden", name: "Harden" },
                        { slug: "amnesia", name: "Amnesia" },
                        { slug: "ember", name: "Ember" },
                        { slug: "rock-throw", name: "Rock Throw" },
                    ],
                    ivs: { hp: 12, atk: 12, spa: 12, def: 12, spd: 12, spe: 12 },
                    evs: { hp: 0, atk: 0, spa: 0, def: 0, spd: 0, spe: 0 },
                },
                {
                    slug: "grovyle",
                    species: "grovyle",
                    level: 31,
                    ability: { slug: "overgrow", name: "Overgrow" },
                    moves: [
                        { slug: "fury-cutter", name: "Fury Cutter" },
                        { slug: "leaf-blade", name: "Leaf Blade" },
                        { slug: "pursuit", name: "Pursuit" },
                        { slug: "screech", name: "Screech" },
                    ],
                    ivs: { hp: 18, atk: 18, spa: 18, def: 18, spd: 18, spe: 18 },
                    evs: { hp: 0, atk: 0, spa: 0, def: 0, spd: 0, spe: 0 },
                },
            ],
            items: [],
        },
        wally_1: {
            trainer: trainers.rse_wally,
            team: [
                {
                    slug: "ralts",
                    species: "ralts",
                    level: 16,
                    ability: { slug: "synchronize", name: "Synchronize" },
                    moves: [
                        { slug: "growl", name: "Growl" },
                        { slug: "confusion", name: "Confusion" },
                        { slug: "double-team", name: "Double Team" },
                        { slug: "teleport", name: "Teleport" },
                    ],
                    ivs: { hp: 3, atk: 3, spa: 3, def: 3, spd: 3, spe: 3 },
                    evs: { hp: 0, atk: 0, spa: 0, def: 0, spd: 0, spe: 0 },
                },
            ],
            items: [],
        },
        wally_2: {
            trainer: trainers.rse_wally,
            team: [
                {
                    slug: "altaria",
                    species: "altaria",
                    level: 44,
                    ability: { slug: "natural-cure", name: "Natural Cure" },
                    moves: [
                        { slug: "aerial-ace", name: "Aerial Ace" },
                        { slug: "safeguard", name: "Safeguard" },
                        { slug: "dragon-breath", name: "Dragon Breath" },
                        { slug: "dragon-dance", name: "Dragon Dance" },
                    ],
                    ivs: { hp: 18, atk: 18, spa: 18, def: 18, spd: 18, spe: 18 },
                    evs: { hp: 0, atk: 0, spa: 0, def: 0, spd: 0, spe: 0 },
                },
                {
                    slug: "delcatty",
                    species: "delcatty",
                    level: 43,
                    ability: { slug: "cute-charm", name: "Cute Charm" },
                    moves: [
                        { slug: "sing", name: "Sing" },
                        { slug: "assist", name: "Assist" },
                        { slug: "charm", name: "Charm" },
                        { slug: "feint-attack", name: "Feint Attack" },
                    ],
                    ivs: { hp: 18, atk: 18, spa: 18, def: 18, spd: 18, spe: 18 },
                    evs: { hp: 0, atk: 0, spa: 0, def: 0, spd: 0, spe: 0 },
                },
                {
                    slug: "roselia",
                    species: "roselia",
                    level: 44,
                    ability: { slug: "poison-point", name: "Poison Point" },
                    moves: [
                        { slug: "magical-leaf", name: "Magical Leaf" },
                        { slug: "leech-seed", name: "Leech Seed" },
                        { slug: "giga-drain", name: "Giga Drain" },
                        { slug: "toxic", name: "Toxic" },
                    ],
                    ivs: { hp: 18, atk: 18, spa: 18, def: 18, spd: 18, spe: 18 },
                    evs: { hp: 0, atk: 0, spa: 0, def: 0, spd: 0, spe: 0 },
                },
                {
                    slug: "magneton",
                    species: "magneton",
                    level: 41,
                    ability: { slug: "magnet-pull", name: "Magnet Pull" },
                    moves: [
                        { slug: "supersonic", name: "Supersonic" },
                        { slug: "thunderbolt", name: "Thunderbolt" },
                        { slug: "tri-attack", name: "Tri Attack" },
                        { slug: "screech", name: "Screech" },
                    ],
                    ivs: { hp: 18, atk: 18, spa: 18, def: 18, spd: 18, spe: 18 },
                    evs: { hp: 0, atk: 0, spa: 0, def: 0, spd: 0, spe: 0 },
                },
                {
                    slug: "gardevoir",
                    species: "gardevoir",
                    level: 45,
                    ability: { slug: "synchronize", name: "Synchronize" },
                    moves: [
                        { slug: "double-team", name: "Double Team" },
                        { slug: "calm-mind", name: "Calm Mind" },
                        { slug: "psychic", name: "Psychic" },
                        { slug: "future-sight", name: "Future Sight" },
                    ],
                    ivs: { hp: 30, atk: 30, spa: 30, def: 30, spd: 30, spe: 30 },
                    evs: { hp: 0, atk: 0, spa: 0, def: 0, spd: 0, spe: 0 },
                },
            ],
            items: ["full-restore", "full-restore"],
        },
        roxanne: {
            trainer: trainers.rse_roxanne,
            team: [
                {
                    slug: "geodude",
                    species: "geodude",
                    level: 12,
                    ability: { slug: "rock-head", name: "Rock Head" },
                    moves: [
                        { slug: "tackle", name: "Tackle" },
                        { slug: "defense-curl", name: "Defense Curl" },
                        { slug: "rock-throw", name: "Rock Throw" },
                        { slug: "rock-tomb", name: "Rock Tomb" },
                    ],
                    ivs: { hp: 12, atk: 12, spa: 12, def: 12, spd: 12, spe: 12 },
                    evs: { hp: 0, atk: 0, spa: 0, def: 0, spd: 0, spe: 0 },
                },
                {
                    slug: "geodude",
                    species: "geodude",
                    level: 12,
                    ability: { slug: "rock-head", name: "Rock Head" },
                    moves: [
                        { slug: "tackle", name: "Tackle" },
                        { slug: "defense-curl", name: "Defense Curl" },
                        { slug: "rock-throw", name: "Rock Throw" },
                        { slug: "rock-tomb", name: "Rock Tomb" },
                    ],
                    ivs: { hp: 12, atk: 12, spa: 12, def: 12, spd: 12, spe: 12 },
                    evs: { hp: 0, atk: 0, spa: 0, def: 0, spd: 0, spe: 0 },
                },
                {
                    slug: "nosepass",
                    species: "nosepass",
                    level: 15,
                    ability: { slug: "sturdy", name: "Sturdy" },
                    moves: [
                        { slug: "block", name: "Block" },
                        { slug: "harden", name: "Harden" },
                        { slug: "tackle", name: "Tackle" },
                        { slug: "rock-tomb", name: "Rock Tomb" },
                    ],
                    item: { slug: "oran-berry", name: "Oran Berry" },
                    ivs: { hp: 24, atk: 24, spa: 24, def: 24, spd: 24, spe: 24 },
                    evs: { hp: 0, atk: 0, spa: 0, def: 0, spd: 0, spe: 0 },
                },
            ],
            items: ["potion", "potion"],
        },
        brawly: {
            trainer: trainers.rse_brawly,
            team: [
                {
                    slug: "machop",
                    species: "machop",
                    level: 16,
                    ability: { slug: "guts", name: "Guts" },
                    moves: [
                        { slug: "karate-chop", name: "Karate Chop" },
                        { slug: "low-kick", name: "Low Kick" },
                        { slug: "seismic-toss", name: "Seismic Toss" },
                        { slug: "bulk-up", name: "Bulk Up" },
                    ],
                    ivs: { hp: 12, atk: 12, spa: 12, def: 12, spd: 12, spe: 12 },
                    evs: { hp: 0, atk: 0, spa: 0, def: 0, spd: 0, spe: 0 },
                },
                {
                    slug: "meditite",
                    species: "meditite",
                    level: 16,
                    ability: { slug: "pure-power", name: "Pure Power" },
                    moves: [
                        { slug: "focus-punch", name: "Focus Punch" },
                        { slug: "light-screen", name: "Light Screen" },
                        { slug: "reflect", name: "Reflect" },
                        { slug: "bulk-up", name: "Bulk Up" },
                    ],
                    ivs: { hp: 12, atk: 12, spa: 12, def: 12, spd: 12, spe: 12 },
                    evs: { hp: 0, atk: 0, spa: 0, def: 0, spd: 0, spe: 0 },
                },
                {
                    slug: "makuhita",
                    species: "makuhita",
                    level: 19,
                    ability: { slug: "thick-fat", name: "Thick Fat" },
                    moves: [
                        { slug: "arm-thrust", name: "Arm Thrust" },
                        { slug: "vital-throw", name: "Vital Throw" },
                        { slug: "reversal", name: "Reversal" },
                        { slug: "bulk-up", name: "Bulk Up" },
                    ],
                    item: { slug: "sitrus-berry", name: "Sitrus Berry" },
                    ivs: { hp: 24, atk: 24, spa: 24, def: 24, spd: 24, spe: 24 },
                    evs: { hp: 0, atk: 0, spa: 0, def: 0, spd: 0, spe: 0 },
                },
            ],
            items: ["super-potion", "super-potion"],
        },
        wattson: {
            trainer: trainers.rse_wattson,
            team: [
                {
                    slug: "voltorb",
                    species: "voltorb",
                    level: 20,
                    ability: { slug: "soundproof", name: "Soundproof" },
                    moves: [
                        { slug: "rollout", name: "Rollout" },
                        { slug: "spark", name: "Spark" },
                        { slug: "self-destruct", name: "Self-Destruct" },
                        { slug: "shock-wave", name: "Shock Wave" },
                    ],
                    ivs: { hp: 24, atk: 24, spa: 24, def: 24, spd: 24, spe: 24 },
                    evs: { hp: 0, atk: 0, spa: 0, def: 0, spd: 0, spe: 0 },
                },
                {
                    slug: "electrike",
                    species: "electrike",
                    level: 20,
                    ability: { slug: "static", name: "Static" },
                    moves: [
                        { slug: "shock-wave", name: "Shock Wave" },
                        { slug: "leer", name: "Leer" },
                        { slug: "quick-attack", name: "Quick Attack" },
                        { slug: "howl", name: "Howl" },
                    ],
                    ivs: { hp: 24, atk: 24, spa: 24, def: 24, spd: 24, spe: 24 },
                    evs: { hp: 0, atk: 0, spa: 0, def: 0, spd: 0, spe: 0 },
                },
                {
                    slug: "magneton",
                    species: "magneton",
                    level: 22,
                    ability: { slug: "magnet-pull", name: "Magnet Pull" },
                    moves: [
                        { slug: "supersonic", name: "Supersonic" },
                        { slug: "thunder-wave", name: "Thunder Wave" },
                        { slug: "shock-wave", name: "Shock Wave" },
                        { slug: "sonic-boom", name: "Sonic Boom" },
                    ],
                    ivs: { hp: 24, atk: 26, spa: 24, def: 24, spd: 24, spe: 24 },
                    evs: { hp: 0, atk: 0, spa: 0, def: 0, spd: 0, spe: 0 },
                },
                {
                    slug: "manectric",
                    species: "manectric",
                    level: 24,
                    ability: { slug: "static", name: "Static" },
                    moves: [
                        { slug: "quick-attack", name: "Quick Attack" },
                        { slug: "shock-wave", name: "Shock Wave" },
                        { slug: "thunder-wave", name: "Thunder Wave" },
                        { slug: "howl", name: "Howl" },
                    ],
                    item: { slug: "sitrus-berry", name: "Sitrus Berry" },
                    ivs: { hp: 30, atk: 30, spa: 30, def: 30, spd: 30, spe: 30 },
                    evs: { hp: 0, atk: 0, spa: 0, def: 0, spd: 0, spe: 0 },
                },
            ],
            items: ["super-potion", "super-potion"],
        },
        flannery: {
            trainer: trainers.rse_flannery,
            team: [
                {
                    slug: "numel",
                    species: "numel",
                    level: 24,
                    ability: { slug: "oblivious", name: "Oblivious" },
                    moves: [
                        { slug: "rollout", name: "Rollout" },
                        { slug: "spark", name: "Spark" },
                        { slug: "self-destruct", name: "Self-Destruct" },
                        { slug: "shock-wave", name: "Shock Wave" },
                    ],
                    ivs: { hp: 24, atk: 24, spa: 24, def: 24, spd: 24, spe: 24 },
                    evs: { hp: 0, atk: 0, spa: 0, def: 0, spd: 0, spe: 0 },
                },
                {
                    slug: "slugma",
                    species: "slugma",
                    level: 24,
                    ability: { slug: "magma-armor", name: "Magma Armor" },
                    moves: [
                        { slug: "shock-wave", name: "Shock Wave" },
                        { slug: "leer", name: "Leer" },
                        { slug: "quick-attack", name: "Quick Attack" },
                        { slug: "howl", name: "Howl" },
                    ],
                    ivs: { hp: 24, atk: 24, spa: 24, def: 24, spd: 24, spe: 24 },
                    evs: { hp: 0, atk: 0, spa: 0, def: 0, spd: 0, spe: 0 },
                },
                {
                    slug: "camerupt",
                    species: "camerupt",
                    level: 26,
                    ability: { slug: "magma-armor", name: "Magma Armor" },
                    moves: [
                        { slug: "supersonic", name: "Supersonic" },
                        { slug: "thunder-wave", name: "Thunder Wave" },
                        { slug: "shock-wave", name: "Shock Wave" },
                        { slug: "sonic-boom", name: "Sonic Boom" },
                    ],
                    ivs: { hp: 30, atk: 30, spa: 30, def: 30, spd: 30, spe: 30 },
                    evs: { hp: 0, atk: 0, spa: 0, def: 0, spd: 0, spe: 0 },
                },
                {
                    slug: "torkoal",
                    species: "torkoal",
                    level: 29,
                    ability: { slug: "white-smoke", name: "White Smoke" },
                    moves: [
                        { slug: "overheat", name: "Overheat" },
                        { slug: "sunny-day", name: "Sunny Day" },
                        { slug: "body-slam", name: "Body Slam" },
                        { slug: "attract", name: "Attract" },
                    ],
                    item: { slug: "white-herb", name: "White Herb" },
                    ivs: { hp: 30, atk: 30, spa: 30, def: 30, spd: 30, spe: 30 },
                    evs: { hp: 0, atk: 0, spa: 0, def: 0, spd: 0, spe: 0 },
                },
            ],
            items: ["super-potion", "super-potion"],
        },
        norman: {
            trainer: trainers.rse_norman,
            team: [
                {
                    slug: "spinda",
                    species: "spinda",
                    level: 27,
                    ability: { slug: "own-tempo", name: "Own Tempo" },
                    moves: [
                        { slug: "facade", name: "Facade" },
                        { slug: "psybeam", name: "Psybeam" },
                        { slug: "teeter-dance", name: "Teeter Dance" },
                        { slug: "encore", name: "Encore" },
                    ],
                    ivs: { hp: 24, atk: 24, spa: 24, def: 24, spd: 24, spe: 24 },
                    evs: { hp: 0, atk: 0, spa: 0, def: 0, spd: 0, spe: 0 },
                },
                {
                    slug: "vigoroth",
                    species: "vigoroth",
                    level: 27,
                    ability: { slug: "vital-spirit", name: "Vital Spirit" },
                    moves: [
                        { slug: "slash", name: "Slash" },
                        { slug: "facade", name: "Facade" },
                        { slug: "feint-attack", name: "Feint Attack" },
                        { slug: "encore", name: "Encore" },
                    ],
                    ivs: { hp: 24, atk: 24, spa: 24, def: 24, spd: 24, spe: 24 },
                    evs: { hp: 0, atk: 0, spa: 0, def: 0, spd: 0, spe: 0 },
                },
                {
                    slug: "linoone",
                    species: "linoone",
                    level: 29,
                    ability: { slug: "pickup", name: "Pickup" },
                    moves: [
                        { slug: "slash", name: "Slash" },
                        { slug: "facade", name: "Facade" },
                        { slug: "headbutt", name: "Headbutt" },
                        { slug: "belly-drum", name: "Belly Drum" },
                    ],
                    ivs: { hp: 24, atk: 24, spa: 24, def: 24, spd: 24, spe: 24 },
                    evs: { hp: 0, atk: 0, spa: 0, def: 0, spd: 0, spe: 0 },
                },
                {
                    slug: "slaking",
                    species: "slaking",
                    level: 31,
                    ability: { slug: "truant", name: "Truant" },
                    moves: [
                        { slug: "facade", name: "Facade" },
                        { slug: "feint-attack", name: "Feint Attack" },
                        { slug: "counter", name: "Counter" },
                        { slug: "yawn", name: "Yawn" },
                    ],
                    item: { slug: "sitrus-berry", name: "Sitrus Berry" },
                    ivs: { hp: 30, atk: 30, spa: 30, def: 30, spd: 30, spe: 30 },
                    evs: { hp: 0, atk: 0, spa: 0, def: 0, spd: 0, spe: 0 },
                },
            ],
            items: ["hyper-potion", "hyper-potion"],
        },
        winona: {
            trainer: trainers.rse_winona,
            team: [
                {
                    slug: "swablu",
                    species: "swablu",
                    level: 29,
                    ability: { slug: "natural-cure", name: "Natural Cure" },
                    moves: [
                        { slug: "aerial-ace", name: "Aerial Ace" },
                        { slug: "perish-song", name: "Perish Song" },
                        { slug: "mirror-move", name: "Mirror Move" },
                        { slug: "safeguard", name: "Safeguard" },
                    ],
                    ivs: { hp: 25, atk: 25, spa: 25, def: 25, spd: 25, spe: 25 },
                    evs: { hp: 0, atk: 0, spa: 0, def: 0, spd: 0, spe: 0 },
                },
                {
                    slug: "tropius",
                    species: "tropius",
                    level: 29,
                    ability: { slug: "chlorophyll", name: "Chlorophyll" },
                    moves: [
                        { slug: "solar-beam", name: "Solar Beam" },
                        { slug: "aerial-ace", name: "Aerial Ace" },
                        { slug: "sunny-day", name: "Sunny Day" },
                        { slug: "synthesis", name: "Synthesis" },
                    ],
                    ivs: { hp: 25, atk: 25, spa: 25, def: 25, spd: 25, spe: 25 },
                    evs: { hp: 0, atk: 0, spa: 0, def: 0, spd: 0, spe: 0 },
                },
                {
                    slug: "pelipper",
                    species: "pelipper",
                    level: 30,
                    ability: { slug: "keen-eye", name: "Keen Eye" },
                    moves: [
                        { slug: "aerial-ace", name: "Aerial Ace" },
                        { slug: "water-gun", name: "Water Gun" },
                        { slug: "supersonic", name: "Supersonic" },
                        { slug: "protect", name: "Protect" },
                    ],
                    ivs: { hp: 25, atk: 25, spa: 25, def: 25, spd: 25, spe: 25 },
                    evs: { hp: 0, atk: 0, spa: 0, def: 0, spd: 0, spe: 0 },
                },
                {
                    slug: "skarmory",
                    species: "skarmory",
                    level: 31,
                    ability: { slug: "keen-eye", name: "Keen Eye" },
                    moves: [
                        { slug: "aerial-ace", name: "Aerial Ace" },
                        { slug: "steel-wing", name: "Steel Wing" },
                        { slug: "fury-attack", name: "Fury Attack" },
                        { slug: "sand-attack", name: "Sand Attack" },
                    ],
                    ivs: { hp: 25, atk: 25, spa: 25, def: 25, spd: 25, spe: 25 },
                    evs: { hp: 0, atk: 0, spa: 0, def: 0, spd: 0, spe: 0 },
                },
                {
                    slug: "altaria",
                    species: "altaria",
                    level: 33,
                    ability: { slug: "natural-cure", name: "Natural Cure" },
                    moves: [
                        { slug: "earthquake", name: "Earthquake" },
                        { slug: "aerial-ace", name: "Aerial Ace" },
                        { slug: "dragon-breath", name: "Dragon Breath" },
                        { slug: "dragon-dance", name: "Dragon Dance" },
                    ],
                    item: { slug: "oran-berry", name: "Oran Berry" },
                    ivs: { hp: 31, atk: 31, spa: 31, def: 31, spd: 31, spe: 31 },
                    evs: { hp: 0, atk: 0, spa: 0, def: 0, spd: 0, spe: 0 },
                },
            ],
            items: ["hyper-potion", "hyper-potion"],
        },
        "tate-and-liza": {
            trainer: trainers.rse_tate_and_liza,
            team: [
                {
                    slug: "xatu",
                    species: "xatu",
                    level: 41,
                    ability: { slug: "synchronize", name: "Synchronize" },
                    moves: [
                        { slug: "psychic", name: "Psychic" },
                        { slug: "calm-mind", name: "Calm Mind" },
                        { slug: "sunny-day", name: "Sunny Day" },
                        { slug: "confuse-ray", name: "Confuse Ray" },
                    ],
                    ivs: { hp: 30, atk: 30, spa: 30, def: 30, spd: 30, spe: 30 },
                    evs: { hp: 0, atk: 0, spa: 0, def: 0, spd: 0, spe: 0 },
                },
                {
                    slug: "claydol",
                    species: "claydol",
                    level: 41,
                    ability: { slug: "levitate", name: "Levitate" },
                    moves: [
                        { slug: "earthquake", name: "Earthquake" },
                        { slug: "ancient-power", name: "Ancient Power" },
                        { slug: "psychic", name: "Psychic" },
                        { slug: "light-screen", name: "Light Screen" },
                    ],
                    ivs: { hp: 30, atk: 30, spa: 30, def: 30, spd: 30, spe: 30 },
                    evs: { hp: 0, atk: 0, spa: 0, def: 0, spd: 0, spe: 0 },
                },
                {
                    slug: "lunatone",
                    species: "lunatone",
                    level: 42,
                    ability: { slug: "levitate", name: "Levitate" },
                    moves: [
                        { slug: "psychic", name: "Psychic" },
                        { slug: "hypnosis", name: "Hypnosis" },
                        { slug: "calm-mind", name: "Calm Mind" },
                        { slug: "light-screen", name: "Light Screen" },
                    ],
                    item: { slug: "sitrus-berry", name: "Sitrus Berry" },
                    ivs: { hp: 30, atk: 30, spa: 30, def: 30, spd: 30, spe: 30 },
                    evs: { hp: 0, atk: 0, spa: 0, def: 0, spd: 0, spe: 0 },
                },
                {
                    slug: "solrock",
                    species: "solrock",
                    level: 42,
                    ability: { slug: "levitate", name: "Levitate" },
                    moves: [
                        { slug: "solar-beam", name: "Solar Beam" },
                        { slug: "psychic", name: "Psychic" },
                        { slug: "flamethrower", name: "Flamethrower" },
                        { slug: "sunny-day", name: "Sunny Day" },
                    ],
                    item: { slug: "sitrus-berry", name: "Sitrus Berry" },
                    ivs: { hp: 30, atk: 30, spa: 30, def: 30, spd: 30, spe: 30 },
                    evs: { hp: 0, atk: 0, spa: 0, def: 0, spd: 0, spe: 0 },
                },
            ],
            items: ["hyper-potion", "hyper-potion", "hyper-potion", "hyper-potion"],
        },
        juan: {
            trainer: trainers.emerald_juan,
            team: [
                {
                    slug: "luvdisc",
                    species: "luvdisc",
                    level: 41,
                    ability: { slug: "swift-swim", name: "Swift Swim" },
                    moves: [
                        { slug: "water-pulse", name: "Water Pulse" },
                        { slug: "flail", name: "Flail" },
                        { slug: "sweet-kiss", name: "Sweet Kiss" },
                        { slug: "attract", name: "Attract" },
                    ],
                    ivs: { hp: 24, atk: 24, spa: 24, def: 24, spd: 24, spe: 24 },
                    evs: { hp: 0, atk: 0, spa: 0, def: 0, spd: 0, spe: 0 },
                },
                {
                    slug: "whiscash",
                    species: "whiscash",
                    level: 41,
                    ability: { slug: "oblivious", name: "Oblivious" },
                    moves: [
                        { slug: "water-pulse", name: "Water Pulse" },
                        { slug: "earthquake", name: "Earthquake" },
                        { slug: "rain-dance", name: "Rain Dance" },
                        { slug: "amnesia", name: "Amnesia" },
                    ],
                    ivs: { hp: 24, atk: 24, spa: 24, def: 24, spd: 24, spe: 24 },
                    evs: { hp: 0, atk: 0, spa: 0, def: 0, spd: 0, spe: 0 },
                },
                {
                    slug: "sealeo",
                    species: "sealeo",
                    level: 43,
                    ability: { slug: "thick-fat", name: "Thick Fat" },
                    moves: [
                        { slug: "aurora-beam", name: "Aurora Beam" },
                        { slug: "water-pulse", name: "Water Pulse" },
                        { slug: "body-slam", name: "Body Slam" },
                        { slug: "encore", name: "Encore" },
                    ],
                    ivs: { hp: 24, atk: 24, spa: 24, def: 24, spd: 24, spe: 24 },
                    evs: { hp: 0, atk: 0, spa: 0, def: 0, spd: 0, spe: 0 },
                },
                {
                    slug: "crawdaunt",
                    species: "crawdaunt",
                    level: 43,
                    ability: { slug: "hyper-cutter", name: "Hyper Cutter" },
                    moves: [
                        { slug: "crabhammer", name: "Crabhammer" },
                        { slug: "water-pulse", name: "Water Pulse" },
                        { slug: "taunt", name: "Taunt" },
                        { slug: "leer", name: "Leer" },
                    ],
                    ivs: { hp: 24, atk: 24, spa: 24, def: 24, spd: 24, spe: 24 },
                    evs: { hp: 0, atk: 0, spa: 0, def: 0, spd: 0, spe: 0 },
                },
                {
                    slug: "kingdra",
                    species: "kingdra",
                    level: 46,
                    ability: { slug: "swift-swim", name: "Swift Swim" },
                    moves: [
                        { slug: "ice-beam", name: "Ice Beam" },
                        { slug: "water-pulse", name: "Water Pulse" },
                        { slug: "double-team", name: "Double Team" },
                        { slug: "rest", name: "Rest" },
                    ],
                    item: { slug: "chesto-berry", name: "Chesto Berry" },
                    ivs: { hp: 30, atk: 30, spa: 30, def: 30, spd: 30, spe: 30 },
                    evs: { hp: 0, atk: 0, spa: 0, def: 0, spd: 0, spe: 0 },
                },
            ],
            items: ["hyper-potion", "hyper-potion"],
        },
        sidney: {
            trainer: trainers.rse_sidney,
            team: [
                {
                    slug: "mightyena",
                    species: "mightyena",
                    level: 46,
                    ability: { slug: "intimidate", name: "Intimidate" },
                    moves: [
                        { slug: "crunch", name: "Crunch" },
                        { slug: "double-edge", name: "Double-Edge" },
                        { slug: "sand-attack", name: "Sand Attack" },
                        { slug: "roar", name: "Roar" },
                    ],
                    ivs: { hp: 30, atk: 30, spa: 30, def: 30, spd: 30, spe: 30 },
                    evs: { hp: 0, atk: 0, spa: 0, def: 0, spd: 0, spe: 0 },
                },
                {
                    slug: "cacturne",
                    species: "cacturne",
                    level: 46,
                    ability: { slug: "sand-veil", name: "Sand Veil" },
                    moves: [
                        { slug: "feint-attack", name: "Feint Attack" },
                        { slug: "needle-arm", name: "Needle Arm" },
                        { slug: "cotton-spore", name: "Cotton Spore" },
                        { slug: "leech-seed", name: "Leech Seed" },
                    ],
                    ivs: { hp: 30, atk: 30, spa: 30, def: 30, spd: 30, spe: 30 },
                    evs: { hp: 0, atk: 0, spa: 0, def: 0, spd: 0, spe: 0 },
                },
                {
                    slug: "shiftry",
                    species: "shiftry",
                    level: 48,
                    ability: { slug: "chlorophyll", name: "Chlorophyll" },
                    moves: [
                        { slug: "extrasensory", name: "Extrasensory" },
                        { slug: "double-team", name: "Double Team" },
                        { slug: "swagger", name: "Swagger" },
                        { slug: "torment", name: "Torment" },
                    ],
                    ivs: { hp: 30, atk: 30, spa: 30, def: 30, spd: 30, spe: 30 },
                    evs: { hp: 0, atk: 0, spa: 0, def: 0, spd: 0, spe: 0 },
                },
                {
                    slug: "crawdaunt",
                    species: "crawdaunt",
                    level: 48,
                    ability: { slug: "hyper-cutter", name: "Hyper Cutter" },
                    moves: [
                        { slug: "surf", name: "Surf" },
                        { slug: "strength", name: "Strength" },
                        { slug: "facade", name: "Facade" },
                        { slug: "swords-dance", name: "Swords Dance" },
                    ],
                    ivs: { hp: 30, atk: 30, spa: 30, def: 30, spd: 30, spe: 30 },
                    evs: { hp: 0, atk: 0, spa: 0, def: 0, spd: 0, spe: 0 },
                },
                {
                    slug: "absol",
                    species: "absol",
                    level: 49,
                    ability: { slug: "pressure", name: "Pressure" },
                    moves: [
                        { slug: "aerial-ace", name: "Aerial Ace" },
                        { slug: "rock-slide", name: "Rock Slide" },
                        { slug: "slash", name: "Slash" },
                        { slug: "swords-dance", name: "Swords Dance" },
                    ],
                    item: { slug: "sitrus-berry", name: "Sitrus Berry" },
                    ivs: { hp: 31, atk: 31, spa: 31, def: 31, spd: 31, spe: 31 },
                    evs: { hp: 0, atk: 0, spa: 0, def: 0, spd: 0, spe: 0 },
                },
            ],
            items: ["full-restore", "full-restore"],
        },
        phoebe: {
            trainer: trainers.rse_phoebe,
            team: [
                {
                    slug: "dusclops",
                    species: "dusclops",
                    level: 48,
                    ability: { slug: "pressure", name: "Pressure" },
                    moves: [
                        { slug: "shadow-punch", name: "Shadow Punch" },
                        { slug: "protect", name: "Protect" },
                        { slug: "confuse-ray", name: "Confuse Ray" },
                        { slug: "curse", name: "Curse" },
                    ],
                    ivs: { hp: 30, atk: 30, spa: 30, def: 30, spd: 30, spe: 30 },
                    evs: { hp: 0, atk: 0, spa: 0, def: 0, spd: 0, spe: 0 },
                },
                {
                    slug: "banette",
                    species: "banette",
                    level: 49,
                    ability: { slug: "insomnia", name: "Insomnia" },
                    moves: [
                        { slug: "shadow-ball", name: "Shadow Ball" },
                        { slug: "feint-attack", name: "Feint Attack" },
                        { slug: "will-o-wisp", name: "Will-O-Wisp" },
                        { slug: "grudge", name: "Grudge" },
                    ],
                    ivs: { hp: 30, atk: 30, spa: 30, def: 30, spd: 30, spe: 30 },
                    evs: { hp: 0, atk: 0, spa: 0, def: 0, spd: 0, spe: 0 },
                },
                {
                    slug: "banette",
                    species: "banette",
                    level: 49,
                    ability: { slug: "insomnia", name: "Insomnia" },
                    moves: [
                        { slug: "shadow-ball", name: "Shadow Ball" },
                        { slug: "psychic", name: "Psychic" },
                        { slug: "thunderbolt", name: "Thunderbolt" },
                        { slug: "facade", name: "Facade" },
                    ],
                    ivs: { hp: 30, atk: 30, spa: 30, def: 30, spd: 30, spe: 30 },
                    evs: { hp: 0, atk: 0, spa: 0, def: 0, spd: 0, spe: 0 },
                },
                {
                    slug: "sableye",
                    species: "sableye",
                    level: 50,
                    ability: { slug: "keen-eye", name: "Keen Eye" },
                    moves: [
                        { slug: "shadow-ball", name: "Shadow Ball" },
                        { slug: "night-shade", name: "Night Shade" },
                        { slug: "feint-attack", name: "Feint Attack" },
                        { slug: "double-team", name: "Double Team" },
                    ],
                    ivs: { hp: 30, atk: 30, spa: 30, def: 30, spd: 30, spe: 30 },
                    evs: { hp: 0, atk: 0, spa: 0, def: 0, spd: 0, spe: 0 },
                },
                {
                    slug: "dusclops",
                    species: "dusclops",
                    level: 51,
                    ability: { slug: "pressure", name: "Pressure" },
                    moves: [
                        { slug: "ice-beam", name: "Ice Beam" },
                        { slug: "shadow-ball", name: "Shadow Ball" },
                        { slug: "rock-slide", name: "Rock Slide" },
                        { slug: "earthquake", name: "Earthquake" },
                    ],
                    item: { slug: "sitrus-berry", name: "Sitrus Berry" },
                    ivs: { hp: 31, atk: 31, spa: 31, def: 31, spd: 31, spe: 31 },
                    evs: { hp: 0, atk: 0, spa: 0, def: 0, spd: 0, spe: 0 },
                },
            ],
            items: ["full-restore", "full-restore"],
        },
        glacia: {
            trainer: trainers.rse_glacia,
            team: [
                {
                    slug: "sealeo",
                    species: "sealeo",
                    level: 50,
                    ability: { slug: "thick-fat", name: "Thick Fat" },
                    moves: [
                        { slug: "encore", name: "Encore" },
                        { slug: "body-slam", name: "Body Slam" },
                        { slug: "hail", name: "Hail" },
                        { slug: "ice-ball", name: "Ice Ball" },
                    ],
                    ivs: { hp: 30, atk: 30, spa: 30, def: 30, spd: 30, spe: 30 },
                    evs: { hp: 0, atk: 0, spa: 0, def: 0, spd: 0, spe: 0 },
                },
                {
                    slug: "glalie",
                    species: "glalie",
                    level: 50,
                    ability: { slug: "inner-focus", name: "Inner Focus" },
                    moves: [
                        { slug: "ice-beam", name: "Ice Beam" },
                        { slug: "icy-wind", name: "Icy Wind" },
                        { slug: "crunch", name: "Crunch" },
                        { slug: "light-screen", name: "Light Screen" },
                    ],
                    ivs: { hp: 30, atk: 30, spa: 30, def: 30, spd: 30, spe: 30 },
                    evs: { hp: 0, atk: 0, spa: 0, def: 0, spd: 0, spe: 0 },
                },
                {
                    slug: "sealeo",
                    species: "sealeo",
                    level: 52,
                    ability: { slug: "thick-fat", name: "Thick Fat" },
                    moves: [
                        { slug: "attract", name: "Attract" },
                        { slug: "double-edge", name: "Double-Edge" },
                        { slug: "hail", name: "Hail" },
                        { slug: "blizzard", name: "Blizzard" },
                    ],
                    ivs: { hp: 30, atk: 30, spa: 30, def: 30, spd: 30, spe: 30 },
                    evs: { hp: 0, atk: 0, spa: 0, def: 0, spd: 0, spe: 0 },
                },
                {
                    slug: "glalie",
                    species: "glalie",
                    level: 52,
                    ability: { slug: "inner-focus", name: "Inner Focus" },
                    moves: [
                        { slug: "ice-beam", name: "Ice Beam" },
                        { slug: "explosion", name: "Explosion" },
                        { slug: "shadow-ball", name: "Shadow Ball" },
                        { slug: "hail", name: "Hail" },
                    ],
                    ivs: { hp: 30, atk: 30, spa: 30, def: 30, spd: 30, spe: 30 },
                    evs: { hp: 0, atk: 0, spa: 0, def: 0, spd: 0, spe: 0 },
                },
                {
                    slug: "walrein",
                    species: "walrein",
                    level: 53,
                    ability: { slug: "thick-fat", name: "Thick Fat" },
                    moves: [
                        { slug: "ice-beam", name: "Ice Beam" },
                        { slug: "surf", name: "Surf" },
                        { slug: "body-slam", name: "Body Slam" },
                        { slug: "sheer-cold", name: "Sheer Cold" },
                    ],
                    item: { slug: "sitrus-berry", name: "Sitrus Berry" },
                    ivs: { hp: 31, atk: 31, spa: 31, def: 31, spd: 31, spe: 31 },
                    evs: { hp: 0, atk: 0, spa: 0, def: 0, spd: 0, spe: 0 },
                },
            ],
            items: ["full-restore", "full-restore"],
        },
        drake: {
            trainer: trainers.rse_drake,
            team: [
                {
                    slug: "shelgon",
                    species: "shelgon",
                    level: 52,
                    ability: { slug: "rock-head", name: "Rock Head" },
                    moves: [
                        { slug: "rock-tomb", name: "Rock Tomb" },
                        { slug: "double-edge", name: "Double-Edge" },
                        { slug: "dragon-claw", name: "Dragon Claw" },
                        { slug: "protect", name: "Protect" },
                    ],
                    ivs: { hp: 30, atk: 30, spa: 30, def: 30, spd: 30, spe: 30 },
                    evs: { hp: 0, atk: 0, spa: 0, def: 0, spd: 0, spe: 0 },
                },
                {
                    slug: "flygon",
                    species: "flygon",
                    level: 53,
                    ability: { slug: "levitate", name: "Levitate" },
                    moves: [
                        { slug: "dragon-breath", name: "Dragon Breath" },
                        { slug: "earthquake", name: "Earthquake" },
                        { slug: "crunch", name: "Crunch" },
                        { slug: "flamethrower", name: "Flamethrower" },
                    ],
                    ivs: { hp: 30, atk: 30, spa: 30, def: 30, spd: 30, spe: 30 },
                    evs: { hp: 0, atk: 0, spa: 0, def: 0, spd: 0, spe: 0 },
                },
                {
                    slug: "kingdra",
                    species: "kingdra",
                    level: 53,
                    ability: { slug: "swift-swim", name: "Swift Swim" },
                    moves: [
                        { slug: "smokescreen", name: "Smokescreen" },
                        { slug: "dragon-dance", name: "Dragon Dance" },
                        { slug: "surf", name: "Surf" },
                        { slug: "body-slam", name: "Body Slam" },
                    ],
                    ivs: { hp: 30, atk: 30, spa: 30, def: 30, spd: 30, spe: 30 },
                    evs: { hp: 0, atk: 0, spa: 0, def: 0, spd: 0, spe: 0 },
                },
                {
                    slug: "altaria",
                    species: "altaria",
                    level: 54,
                    ability: { slug: "natural-cure", name: "Natural Cure" },
                    moves: [
                        { slug: "double-edge", name: "Double-Edge" },
                        { slug: "dragon-breath", name: "Dragon Breath" },
                        { slug: "dragon-dance", name: "Dragon Dance" },
                        { slug: "aerial-ace", name: "Aerial Ace" },
                    ],
                    ivs: { hp: 30, atk: 30, spa: 30, def: 30, spd: 30, spe: 30 },
                    evs: { hp: 0, atk: 0, spa: 0, def: 0, spd: 0, spe: 0 },
                },
                {
                    slug: "salamence",
                    species: "salamence",
                    level: 55,
                    ability: { slug: "intimidate", name: "Intimidate" },
                    moves: [
                        { slug: "flamethrower", name: "Flamethrower" },
                        { slug: "dragon-claw", name: "Dragon Claw" },
                        { slug: "rock-slide", name: "Rock Slide" },
                        { slug: "crunch", name: "Crunch" },
                    ],
                    ivs: { hp: 31, atk: 31, spa: 31, def: 31, spd: 31, spe: 31 },
                    evs: { hp: 0, atk: 0, spa: 0, def: 0, spd: 0, spe: 0 },
                },
            ],
            items: ["full-restore", "full-restore"],
        },
        wallace: {
            trainer: trainers.emerald_wallace,
            team: [
                {
                    slug: "wailord",
                    species: "wailord",
                    level: 57,
                    ability: { slug: "water-veil", name: "Water Veil" },
                    moves: [
                        { slug: "rain-dance", name: "Rain Dance" },
                        { slug: "water-spout", name: "Water Spout" },
                        { slug: "double-edge", name: "Double-Edge" },
                        { slug: "blizzard", name: "Blizzard" },
                    ],
                    ivs: { hp: 30, atk: 30, spa: 30, def: 30, spd: 30, spe: 30 },
                    evs: { hp: 0, atk: 0, spa: 0, def: 0, spd: 0, spe: 0 },
                },
                {
                    slug: "tentacruel",
                    species: "tentacruel",
                    level: 55,
                    ability: { slug: "clear-body", name: "Clear Body" },
                    moves: [
                        { slug: "toxic", name: "Toxic" },
                        { slug: "hydro-pump", name: "Hydro Pump" },
                        { slug: "sludge-bomb", name: "Sludge Bomb" },
                        { slug: "ice-beam", name: "Ice Beam" },
                    ],
                    ivs: { hp: 30, atk: 30, spa: 30, def: 30, spd: 30, spe: 30 },
                    evs: { hp: 0, atk: 0, spa: 0, def: 0, spd: 0, spe: 0 },
                },
                {
                    slug: "ludicolo",
                    species: "ludicolo",
                    level: 56,
                    ability: { slug: "swift-swim", name: "Swift Swim" },
                    moves: [
                        { slug: "giga-drain", name: "Giga Drain" },
                        { slug: "surf", name: "Surf" },
                        { slug: "leech-seed", name: "Leech Seed" },
                        { slug: "double-team", name: "Double Team" },
                    ],
                    ivs: { hp: 30, atk: 30, spa: 30, def: 30, spd: 30, spe: 30 },
                    evs: { hp: 0, atk: 0, spa: 0, def: 0, spd: 0, spe: 0 },
                },
                {
                    slug: "whiscash",
                    species: "whiscash",
                    level: 56,
                    ability: { slug: "oblivious", name: "Oblivious" },
                    moves: [
                        { slug: "earthquake", name: "Earthquake" },
                        { slug: "surf", name: "Surf" },
                        { slug: "amnesia", name: "Amnesia" },
                        { slug: "hyper-beam", name: "Hyper Beam" },
                    ],
                    ivs: { hp: 30, atk: 30, spa: 30, def: 30, spd: 30, spe: 30 },
                    evs: { hp: 0, atk: 0, spa: 0, def: 0, spd: 0, spe: 0 },
                },
                {
                    slug: "gyarados",
                    species: "gyarados",
                    level: 56,
                    ability: { slug: "intimidate", name: "Intimidate" },
                    moves: [
                        { slug: "dragon-dance", name: "Dragon Dance" },
                        { slug: "earthquake", name: "Earthquake" },
                        { slug: "hyper-beam", name: "Hyper Beam" },
                        { slug: "surf", name: "Surf" },
                    ],
                    ivs: { hp: 30, atk: 30, spa: 30, def: 30, spd: 30, spe: 30 },
                    evs: { hp: 0, atk: 0, spa: 0, def: 0, spd: 0, spe: 0 },
                },
                {
                    slug: "milotic",
                    species: "milotic",
                    level: 58,
                    ability: { slug: "marvel-scale", name: "Marvel Scale" },
                    moves: [
                        { slug: "recover", name: "Recover" },
                        { slug: "surf", name: "Surf" },
                        { slug: "ice-beam", name: "Ice Beam" },
                        { slug: "toxic", name: "Toxic" },
                    ],
                    item: { slug: "sitrus-berry", name: "Sitrus Berry" },
                    ivs: { hp: 31, atk: 31, spa: 31, def: 31, spd: 31, spe: 31 },
                    evs: { hp: 0, atk: 0, spa: 0, def: 0, spd: 0, spe: 0 },
                },
            ],
            items: ["full-restore", "full-restore", "full-restore", "full-restore"],
        },
        tabitha_1: {
            trainer: trainers.rse_tabitha,
            team: [
                {
                    slug: "numel",
                    species: "numel",
                    level: 18,
                    ability: { slug: "oblivious", name: "Oblivious" },
                    moves: [
                        { slug: "growl", name: "Growl" },
                        { slug: "tackle", name: "Tackle" },
                        { slug: "ember", name: "Ember" },
                    ],
                    ivs: { hp: 6, atk: 6, spa: 6, def: 6, spd: 6, spe: 6 },
                    evs: { hp: 0, atk: 0, spa: 0, def: 0, spd: 0, spe: 0 },
                },
                {
                    slug: "poochyena",
                    species: "poochyena",
                    level: 20,
                    ability: { slug: "run-away", name: "Run Away" },
                    moves: [
                        { slug: "howl", name: "Howl" },
                        { slug: "sand-attack", name: "Sand Attack" },
                        { slug: "bite", name: "Bite" },
                        { slug: "odor-sleuth", name: "Odor Sleuth" },
                    ],
                    ivs: { hp: 6, atk: 6, spa: 6, def: 6, spd: 6, spe: 6 },
                    evs: { hp: 0, atk: 0, spa: 0, def: 0, spd: 0, spe: 0 },
                },
                {
                    slug: "numel",
                    species: "numel",
                    level: 22,
                    ability: { slug: "oblivious", name: "Oblivious" },
                    moves: [
                        { slug: "growl", name: "Growl" },
                        { slug: "tackle", name: "Tackle" },
                        { slug: "ember", name: "Ember" },
                        { slug: "magnitude", name: "Magnitude" },
                    ],
                    ivs: { hp: 6, atk: 6, spa: 6, def: 6, spd: 6, spe: 6 },
                    evs: { hp: 0, atk: 0, spa: 0, def: 0, spd: 0, spe: 0 },
                },
                {
                    slug: "zubat",
                    species: "zubat",
                    level: 22,
                    ability: { slug: "inner-focus", name: "Inner Focus" },
                    moves: [
                        { slug: "supersonic", name: "Supersonic" },
                        { slug: "astonish", name: "Astonish" },
                        { slug: "bite", name: "Bite" },
                        { slug: "wing-attack", name: "Wing Attack" },
                    ],
                    ivs: { hp: 6, atk: 6, spa: 6, def: 6, spd: 6, spe: 6 },
                    evs: { hp: 0, atk: 0, spa: 0, def: 0, spd: 0, spe: 0 },
                },
            ],
            items: [],
        },
        tabitha_2: {
            trainer: trainers.rse_tabitha,
            team: [
                {
                    slug: "numel",
                    species: "numel",
                    level: 26,
                    ability: { slug: "oblivious", name: "Oblivious" },
                    moves: [
                        { slug: "tackle", name: "Tackle" },
                        { slug: "magnitude", name: "Magnitude" },
                        { slug: "ember", name: "Ember" },
                        { slug: "focus-energy", name: "Focus Energy" },
                    ],
                    ivs: { hp: 9, atk: 9, spa: 9, def: 9, spd: 9, spe: 9 },
                    evs: { hp: 0, atk: 0, spa: 0, def: 0, spd: 0, spe: 0 },
                },
                {
                    slug: "mightyena",
                    species: "mightyena",
                    level: 28,
                    ability: { slug: "intimidate", name: "Intimidate" },
                    moves: [
                        { slug: "bite", name: "Bite" },
                        { slug: "odor-sleuth", name: "Odor Sleuth" },
                        { slug: "roar", name: "Roar" },
                        { slug: "swagger", name: "Swagger" },
                    ],
                    ivs: { hp: 9, atk: 9, spa: 9, def: 9, spd: 9, spe: 9 },
                    evs: { hp: 0, atk: 0, spa: 0, def: 0, spd: 0, spe: 0 },
                },
                {
                    slug: "zubat",
                    species: "zubat",
                    level: 30,
                    ability: { slug: "inner-focus", name: "Inner Focus" },
                    moves: [
                        { slug: "astonish", name: "Astonish" },
                        { slug: "confuse-ray", name: "Confuse Ray" },
                        { slug: "bite", name: "Bite" },
                        { slug: "wing-attack", name: "Wing Attack" },
                    ],
                    ivs: { hp: 6, atk: 6, spa: 6, def: 6, spd: 6, spe: 6 },
                    evs: { hp: 0, atk: 0, spa: 0, def: 0, spd: 0, spe: 0 },
                },
                {
                    slug: "camerupt",
                    species: "camerupt",
                    level: 33,
                    ability: { slug: "magma-armor", name: "Magma Armor" },
                    moves: [
                        { slug: "focus-energy", name: "Focus Energy" },
                        { slug: "take-down", name: "Take Down" },
                        { slug: "amnesia", name: "Amnesia" },
                        { slug: "rock-slide", name: "Rock Slide" },
                    ],
                    ivs: { hp: 9, atk: 9, spa: 9, def: 9, spd: 9, spe: 9 },
                    evs: { hp: 0, atk: 0, spa: 0, def: 0, spd: 0, spe: 0 },
                },
            ],
            items: [],
        },
        maxie_1: {
            trainer: trainers.rse_maxie,
            team: [
                {
                    slug: "mightyena",
                    species: "mightyena",
                    level: 24,
                    ability: { slug: "intimidate", name: "Intimidate" },
                    moves: [
                        { slug: "bite", name: "Bite" },
                        { slug: "sand-attack", name: "Sand Attack" },
                        { slug: "roar", name: "Roar" },
                        { slug: "odor-sleuth", name: "Odor Sleuth" },
                    ],
                    ivs: { hp: 18, atk: 18, spa: 18, def: 18, spd: 18, spe: 18 },
                    evs: { hp: 0, atk: 0, spa: 0, def: 0, spd: 0, spe: 0 },
                },
                {
                    slug: "zubat",
                    species: "zubat",
                    level: 24,
                    ability: { slug: "inner-focus", name: "Inner Focus" },
                    moves: [
                        { slug: "wing-attack", name: "Wing Attack" },
                        { slug: "bite", name: "Bite" },
                        { slug: "astonish", name: "Astonish" },
                        { slug: "supersonic", name: "Supersonic" },
                    ],
                    ivs: { hp: 18, atk: 18, spa: 18, def: 18, spd: 18, spe: 18 },
                    evs: { hp: 0, atk: 0, spa: 0, def: 0, spd: 0, spe: 0 },
                },
                {
                    slug: "camerupt",
                    species: "camerupt",
                    level: 25,
                    ability: { slug: "magma-armor", name: "Magma Armor" },
                    moves: [
                        { slug: "magnitude", name: "Magnitude" },
                        { slug: "ember", name: "Ember" },
                        { slug: "tackle", name: "Tackle" },
                        { slug: "focus-energy", name: "Focus Energy" },
                    ],
                    ivs: { hp: 9, atk: 9, spa: 9, def: 9, spd: 9, spe: 9 },
                    evs: { hp: 0, atk: 0, spa: 0, def: 0, spd: 0, spe: 0 },
                },
            ],
            items: ["super-potion", "super-potion"],
        },
        maxie_2: {
            trainer: trainers.rse_maxie,
            team: [
                {
                    slug: "mightyena",
                    species: "mightyena",
                    level: 37,
                    ability: { slug: "intimidate", name: "Intimidate" },
                    moves: [
                        { slug: "roar", name: "Roar" },
                        { slug: "swagger", name: "Swagger" },
                        { slug: "scary-face", name: "Scary Face" },
                        { slug: "take-down", name: "Take Down" },
                    ],
                    ivs: { hp: 18, atk: 18, spa: 18, def: 18, spd: 18, spe: 18 },
                    evs: { hp: 0, atk: 0, spa: 0, def: 0, spd: 0, spe: 0 },
                },
                {
                    slug: "crobat",
                    species: "crobat",
                    level: 38,
                    ability: { slug: "inner-focus", name: "Inner Focus" },
                    moves: [
                        { slug: "bite", name: "Bite" },
                        { slug: "confuse-ray", name: "Confuse Ray" },
                        { slug: "wing-attack", name: "Wing Attack" },
                        { slug: "air-cutter", name: "Air Cutter" },
                    ],
                    ivs: { hp: 18, atk: 18, spa: 18, def: 18, spd: 18, spe: 18 },
                    evs: { hp: 0, atk: 0, spa: 0, def: 0, spd: 0, spe: 0 },
                },
                {
                    slug: "camerupt",
                    species: "camerupt",
                    level: 39,
                    ability: { slug: "magma-armor", name: "Magma Armor" },
                    moves: [
                        { slug: "take-down", name: "Take Down" },
                        { slug: "amnesia", name: "Amnesia" },
                        { slug: "rock-slide", name: "Rock Slide" },
                        { slug: "earthquake", name: "Earthquake" },
                    ],
                    ivs: { hp: 18, atk: 18, spa: 18, def: 18, spd: 18, spe: 18 },
                    evs: { hp: 0, atk: 0, spa: 0, def: 0, spd: 0, spe: 0 },
                },
            ],
            items: ["super-potion", "super-potion"],
        },
        tabitha_maxie: {
            trainer: [trainers.rse_tabitha, trainers.rse_maxie],
            team: [
                {
                    slug: "mightyena",
                    species: "mightyena",
                    level: 42,
                    ability: { slug: "intimidate", name: "Intimidate" },
                    moves: [
                        { slug: "take-down", name: "Take Down" },
                        { slug: "swagger", name: "Swagger" },
                        { slug: "scary-face", name: "Scary Face" },
                        { slug: "taunt", name: "Taunt" },
                    ],
                    ivs: { hp: 18, atk: 18, spa: 18, def: 18, spd: 18, spe: 18 },
                    evs: { hp: 0, atk: 0, spa: 0, def: 0, spd: 0, spe: 0 },
                },
                {
                    slug: "camerupt",
                    species: "camerupt",
                    level: 36,
                    ability: { slug: "magma-armor", name: "Magma Armor" },
                    moves: [
                        { slug: "rock-slide", name: "Rock Slide" },
                        { slug: "take-down", name: "Take Down" },
                        { slug: "amnesia", name: "Amnesia" },
                        { slug: "focus-energy", name: "Focus Energy" },
                    ],
                    ivs: { hp: 12, atk: 12, spa: 12, def: 12, spd: 12, spe: 12 },
                    evs: { hp: 0, atk: 0, spa: 0, def: 0, spd: 0, spe: 0 },
                },
                {
                    slug: "crobat",
                    species: "crobat",
                    level: 43,
                    ability: { slug: "inner-focus", name: "Inner Focus" },
                    moves: [
                        { slug: "air-cutter", name: "Air Cutter" },
                        { slug: "wing-attack", name: "Wing Attack" },
                        { slug: "confuse-ray", name: "Confuse Ray" },
                        { slug: "mean-look", name: "Mean Look" },
                    ],
                    ivs: { hp: 18, atk: 18, spa: 18, def: 18, spd: 18, spe: 18 },
                    evs: { hp: 0, atk: 0, spa: 0, def: 0, spd: 0, spe: 0 },
                },
                {
                    slug: "mightyena",
                    species: "mightyena",
                    level: 38,
                    ability: { slug: "intimidate", name: "Intimidate" },
                    moves: [
                        { slug: "take-down", name: "Take Down" },
                        { slug: "swagger", name: "Swagger" },
                        { slug: "roar", name: "Roar" },
                        { slug: "scary-face", name: "Scary Face" },
                    ],
                    ivs: { hp: 12, atk: 12, spa: 12, def: 12, spd: 12, spe: 12 },
                    evs: { hp: 0, atk: 0, spa: 0, def: 0, spd: 0, spe: 0 },
                },
                {
                    slug: "camerupt",
                    species: "camerupt",
                    level: 44,
                    ability: { slug: "magma-armor", name: "Magma Armor" },
                    moves: [
                        { slug: "take-down", name: "Take Down" },
                        { slug: "amnesia", name: "Amnesia" },
                        { slug: "rock-slide", name: "Rock Slide" },
                        { slug: "earthquake", name: "Earthquake" },
                    ],
                    ivs: { hp: 18, atk: 18, spa: 18, def: 18, spd: 18, spe: 18 },
                    evs: { hp: 0, atk: 0, spa: 0, def: 0, spd: 0, spe: 0 },
                },
                {
                    slug: "golbat",
                    species: "golbat",
                    level: 40,
                    ability: { slug: "inner-focus", name: "Inner Focus" },
                    moves: [
                        { slug: "air-cutter", name: "Air Cutter" },
                        { slug: "wing-attack", name: "Wing Attack" },
                        { slug: "bite", name: "Bite" },
                        { slug: "confuse-ray", name: "Confuse Ray" },
                    ],
                    ivs: { hp: 12, atk: 12, spa: 12, def: 12, spd: 12, spe: 12 },
                    evs: { hp: 0, atk: 0, spa: 0, def: 0, spd: 0, spe: 0 },
                },
            ],
            items: [],
        },
        shelly: {
            trainer: trainers.rse_shelly,
            team: [
                {
                    slug: "carvanha",
                    species: "carvanha",
                    level: 28,
                    ability: { slug: "rough-skin", name: "Rough Skin" },
                    moves: [
                        { slug: "focus-energy", name: "Focus Energy" },
                        { slug: "scary-face", name: "Scary Face" },
                        { slug: "crunch", name: "Crunch" },
                        { slug: "screech", name: "Screech" },
                    ],
                    ivs: { hp: 6, atk: 6, spa: 6, def: 6, spd: 6, spe: 6 },
                    evs: { hp: 0, atk: 0, spa: 0, def: 0, spd: 0, spe: 0 },
                },
                {
                    slug: "mightyena",
                    species: "mightyena",
                    level: 28,
                    ability: { slug: "intimidate", name: "Intimidate" },
                    moves: [
                        { slug: "bite", name: "Bite" },
                        { slug: "odor-sleuth", name: "Odor Sleuth" },
                        { slug: "roar", name: "Roar" },
                        { slug: "swagger", name: "Swagger" },
                    ],
                    ivs: { hp: 6, atk: 6, spa: 6, def: 6, spd: 6, spe: 6 },
                    evs: { hp: 0, atk: 0, spa: 0, def: 0, spd: 0, spe: 0 },
                },
            ],
            items: [],
        },
        matt: {
            trainer: trainers.rse_matt,
            team: [
                {
                    slug: "mightyena",
                    species: "mightyena",
                    level: 34,
                    ability: { slug: "intimidate", name: "Intimidate" },
                    moves: [
                        { slug: "odor-sleuth", name: "Odor Sleuth" },
                        { slug: "roar", name: "Roar" },
                        { slug: "swagger", name: "Swagger" },
                        { slug: "scary-face", name: "Scary Face" },
                    ],
                    ivs: { hp: 6, atk: 6, spa: 6, def: 6, spd: 6, spe: 6 },
                    evs: { hp: 0, atk: 0, spa: 0, def: 0, spd: 0, spe: 0 },
                },
                {
                    slug: "golbat",
                    species: "golbat",
                    level: 34,
                    ability: { slug: "inner-focus", name: "Inner Focus" },
                    moves: [
                        { slug: "astonish", name: "Astonish" },
                        { slug: "confuse-ray", name: "Confuse Ray" },
                        { slug: "bite", name: "Bite" },
                        { slug: "wing-attack", name: "Wing Attack" },
                    ],
                    ivs: { hp: 6, atk: 6, spa: 6, def: 6, spd: 6, spe: 6 },
                    evs: { hp: 0, atk: 0, spa: 0, def: 0, spd: 0, spe: 0 },
                },
            ],
            items: ["super-potion"],
        },
        archie: {
            trainer: trainers.rse_archie,
            team: [
                {
                    slug: "mightyena",
                    species: "mightyena",
                    level: 41,
                    ability: { slug: "intimidate", name: "Intimidate" },
                    moves: [
                        { slug: "take-down", name: "Take Down" },
                        { slug: "roar", name: "Roar" },
                        { slug: "swagger", name: "Swagger" },
                        { slug: "scary-face", name: "Scary Face" },
                    ],
                    ivs: { hp: 18, atk: 18, spa: 18, def: 18, spd: 18, spe: 18 },
                    evs: { hp: 0, atk: 0, spa: 0, def: 0, spd: 0, spe: 0 },
                },
                {
                    slug: "crobat",
                    species: "crobat",
                    level: 41,
                    ability: { slug: "inner-focus", name: "Inner Focus" },
                    moves: [
                        { slug: "bite", name: "Bite" },
                        { slug: "confuse-ray", name: "Confuse Ray" },
                        { slug: "air-cutter", name: "Air Cutter" },
                        { slug: "wing-attack", name: "Wing Attack" },
                    ],
                    ivs: { hp: 18, atk: 18, spa: 18, def: 18, spd: 18, spe: 18 },
                    evs: { hp: 0, atk: 0, spa: 0, def: 0, spd: 0, spe: 0 },
                },
                {
                    slug: "sharpedo",
                    species: "sharpedo",
                    level: 43,
                    ability: { slug: "rough-skin", name: "Rough Skin" },
                    moves: [
                        { slug: "screech", name: "Screech" },
                        { slug: "slash", name: "Slash" },
                        { slug: "swagger", name: "Swagger" },
                        { slug: "taunt", name: "Taunt" },
                    ],
                    ivs: { hp: 18, atk: 18, spa: 18, def: 18, spd: 18, spe: 18 },
                    evs: { hp: 0, atk: 0, spa: 0, def: 0, spd: 0, spe: 0 },
                },
            ],
            items: ["super-potion", "super-potion"],
        },
    },
    "heartgold-soulsilver": {
        silver_1_chikorita: {
            trainer: trainers.hgss_silver,
            team: [
                {
                    slug: "cyndaquil",
                    species: "cyndaquil",
                    level: 5,
                    ability: { slug: "blaze", name: "Blaze" },
                    moves: [
                        { slug: "tackle", name: "Tackle" },
                        { slug: "leer", name: "Leer" },
                    ],
                    ivs: { hp: 0, atk: 0, spa: 0, def: 0, spd: 0, spe: 0 },
                    evs: { hp: 0, atk: 0, spa: 0, def: 0, spd: 0, spe: 0 },
                },
            ],
            items: [],
        },
        silver_1_cyndaquil: {
            trainer: trainers.hgss_silver,
            team: [
                {
                    slug: "totodile",
                    species: "totodile",
                    level: 5,
                    ability: { slug: "torrent", name: "Torrent" },
                    moves: [
                        { slug: "scratch", name: "Scratch" },
                        { slug: "leer", name: "Leer" },
                    ],
                    ivs: { hp: 0, atk: 0, spa: 0, def: 0, spd: 0, spe: 0 },
                    evs: { hp: 0, atk: 0, spa: 0, def: 0, spd: 0, spe: 0 },
                },
            ],
            items: [],
        },
        silver_1_totodile: {
            trainer: trainers.hgss_silver,
            team: [
                {
                    slug: "chikorita",
                    species: "chikorita",
                    level: 5,
                    ability: { slug: "overgrow", name: "Overgrow" },
                    moves: [
                        { slug: "tackle", name: "Tackle" },
                        { slug: "growl", name: "Growl" },
                    ],
                    ivs: { hp: 0, atk: 0, spa: 0, def: 0, spd: 0, spe: 0 },
                    evs: { hp: 0, atk: 0, spa: 0, def: 0, spd: 0, spe: 0 },
                },
            ],
            items: [],
        },
        elder_li: {
            trainer: trainers.hgss_elder_li,
            team: [
                {
                    slug: "bellsprout",
                    species: "bellsprout",
                    level: 7,
                    ability: { slug: "chlorophyll", name: "Chlorophyll" },
                    moves: [
                        { slug: "vine-whip", name: "Vine Whip" },
                        { slug: "growth", name: "Growth" },
                    ],
                    ivs: { hp: 0, atk: 0, spa: 0, def: 0, spd: 0, spe: 0 },
                    evs: { hp: 0, atk: 0, spa: 0, def: 0, spd: 0, spe: 0 },
                },
                {
                    slug: "bellsprout",
                    species: "bellsprout",
                    level: 7,
                    ability: { slug: "chlorophyll", name: "Chlorophyll" },
                    moves: [
                        { slug: "vine-whip", name: "Vine Whip" },
                        { slug: "growth", name: "Growth" },
                    ],
                    ivs: { hp: 0, atk: 0, spa: 0, def: 0, spd: 0, spe: 0 },
                    evs: { hp: 0, atk: 0, spa: 0, def: 0, spd: 0, spe: 0 },
                },
                {
                    slug: "hoothoot",
                    species: "hoothoot",
                    level: 10,
                    ability: { slug: "insomnia", name: "Insomnia" },
                    moves: [
                        { slug: "growl", name: "Growl" },
                        { slug: "hypnosis", name: "Hypnosis" },
                        { slug: "peck", name: "Peck" },
                    ],
                    ivs: { hp: 0, atk: 0, spa: 0, def: 0, spd: 0, spe: 0 },
                    evs: { hp: 0, atk: 0, spa: 0, def: 0, spd: 0, spe: 0 },
                },
            ],
            items: [],
        },
        falkner: {
            trainer: trainers.hgss_falkner,
            team: [
                {
                    slug: "pidgey",
                    species: "pidgey",
                    level: 9,
                    ability: { slug: "keen-eye", name: "Keen Eye" },
                    moves: [
                        { slug: "tackle", name: "Tackle" },
                        { slug: "sand-attack", name: "Sand Attack" },
                    ],
                    ivs: { hp: 0, atk: 0, spa: 0, def: 0, spd: 0, spe: 0 },
                    evs: { hp: 0, atk: 0, spa: 0, def: 0, spd: 0, spe: 0 },
                },
                {
                    slug: "pidgeotto",
                    species: "pidgeotto",
                    level: 13,
                    ability: { slug: "keen-eye", name: "Keen Eye" },
                    moves: [
                        { slug: "tackle", name: "Tackle" },
                        { slug: "roost", name: "Roost" },
                        { slug: "gust", name: "Gust" },
                    ],
                    ivs: { hp: 0, atk: 0, spa: 0, def: 0, spd: 0, spe: 0 },
                    evs: { hp: 0, atk: 0, spa: 0, def: 0, spd: 0, spe: 0 },
                },
            ],
            items: [],
        },
    },
};
export default battles;
