const priorities: { [group: string]: string[] } = {
    generations: [
        "generation-i",
        "generation-ii",
        "generation-iii",
        "generation-iv",
        "generation-v",
        "generation-vi",
        "generation-vii",
        "generation-viii",
        "generation-ix",
    ],
    groups: [
        "ruby-sapphire",
        "emerald",
        "firered-leafgreen",
        "diamond-pearl",
        "platinum",
        "heartgold-soulsilver",
        "black-white",
        "black-2-white-2",
        "x-y",
        "omega-ruby-alpha-sapphire",
        "sun-moon",
        "ultra-sun-ultra-moon",
        "lets-go-pikachu-lets-go-eevee",
        "sword-shield",
        "isle-of-armor",
        "crown-tundra",
        "brilliant-diamond-and-shining-pearl",
        "legends-arceus",
        "scarlet-violet",
        "the-teal-mask",
    ],
};

export default priorities;
